// 主题包（Theme Pack）定义：从 uitest/styles 下的 12 个风格页面提取的配色与样式 token
// 每个 token 均为可选；未设置的 token 表示该项保持 CSS 默认样式
// 主题包通过 CSS 变量 + .dingpan-container.pack-active 覆盖层生效，
// 只影响盯盘页最外层组件（卡片/子项/按钮/标签），弹窗与 Tooltip 由 antd Portal
// 渲染在 body 下，天然不受影响

export const THEME_PACK_TOKEN_KEYS = [
    'pageBg',            // 页面背景颜色（支持渐变）
    'fontFamily',        // 全局字体 family
    'numberFontFamily',  // 数字字体 family
    // 容器卡片
    'cardBg',            // 容器卡片背景
    'cardBorderColor',   // 容器卡片边框颜色
    'cardBorderWidth',   // 容器卡片边框粗细
    'cardRadius',        // 容器卡片圆角
    'cardShadow',        // 容器卡片阴影
    // 标题/描述
    'titleColor',        // 标题字体颜色
    'descColor',         // 描述字体颜色
    // 子 item
    'itemBg',            // 子 item 背景色
    'itemTitleColor',    // 子 item 标题颜色
    'itemDescColor',     // 子 item 描述字体颜色
    'itemBorderColor',   // 子 item 边框颜色
    'itemBorderStyle',   // 子 item 边框样式（solid/dashed/dotted）
    'itemBorderWidth',   // 子 item 边框粗细
    'itemRadius',        // 子 item 圆角
    // 涨跌
    'upColor',           // 涨幅红色
    'downColor',         // 跌幅绿色
    'upBg',              // 涨幅标签底色（可选，默认由 upColor 派生）
    'downBg',            // 跌幅标签底色（可选，默认由 downColor 派生）
    // 按钮
    'btnBg',             // 按钮背景
    'btnColor',          // 按钮字体颜色
    'btnFontFamily',     // 按钮字体 family
    'btnRadius',         // 按钮圆角
    'btnBorderColor',    // 按钮边框颜色
    'btnBorderStyle',    // 按钮边框样式
    'btnBorderWidth',    // 按钮边框粗细
    'btnShadow',         // 按钮阴影
    // 标签 Tag
    'tagBg',             // tag 背景颜色
    'tagColor',          // tag 字体颜色
    'tagFontFamily',     // tag 字体 family
    'tagBorderColor',    // tag 边框颜色
    'tagBorderStyle',    // tag 边框样式
    'tagBorderWidth',    // tag 边框粗细
    'tagRadius',         // tag 圆角
];

// token -> CSS 变量名映射
const TOKEN_TO_VAR = {
    pageBg: '--dp-page-bg',
    fontFamily: '--dp-font-family',
    numberFontFamily: '--dp-number-font-family',
    cardBg: '--dp-card-bg',
    cardBorderColor: '--dp-card-border-color',
    cardBorderWidth: '--dp-card-border-width',
    cardRadius: '--dp-card-radius',
    cardShadow: '--dp-card-shadow',
    titleColor: '--dp-title-color',
    descColor: '--dp-desc-color',
    itemBg: '--dp-item-bg',
    itemTitleColor: '--dp-item-title-color',
    itemDescColor: '--dp-item-desc-color',
    itemBorderColor: '--dp-item-border-color',
    itemBorderStyle: '--dp-item-border-style',
    itemBorderWidth: '--dp-item-border-width',
    itemRadius: '--dp-item-radius',
    upColor: '--dp-up-color',
    downColor: '--dp-down-color',
    upBg: '--dp-up-bg',
    downBg: '--dp-down-bg',
    btnBg: '--dp-btn-bg',
    btnColor: '--dp-btn-color',
    btnFontFamily: '--dp-btn-font-family',
    btnRadius: '--dp-btn-radius',
    btnBorderColor: '--dp-btn-border-color',
    btnBorderStyle: '--dp-btn-border-style',
    btnBorderWidth: '--dp-btn-border-width',
    btnShadow: '--dp-btn-shadow',
    tagBg: '--dp-tag-bg',
    tagColor: '--dp-tag-color',
    tagFontFamily: '--dp-tag-font-family',
    tagBorderColor: '--dp-tag-border-color',
    tagBorderStyle: '--dp-tag-border-style',
    tagBorderWidth: '--dp-tag-border-width',
    tagRadius: '--dp-tag-radius',
};

// hex -> rgba（用于派生涨跌标签底色；非 hex 值返回中性半透明灰）
export const hexToRgba = (hex, alpha = 0.12) => {
    if (typeof hex === 'string' && /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(hex)) {
        let h = hex.slice(1);
        if (h.length === 3) h = h.split('').map(c => c + c).join('');
        const r = parseInt(h.slice(0, 2), 16);
        const g = parseInt(h.slice(2, 4), 16);
        const b = parseInt(h.slice(4, 6), 16);
        return `rgba(${r}, ${g}, ${b}, ${alpha})`;
    }
    return `rgba(127, 127, 127, ${alpha})`;
};

// 主题包列表（默认主题不在列表内，id 为 '' 表示默认/当前样式）
export const THEME_PACKS = [
    {
        id: 'liquid-glass',
        name: '流体玻璃',
        desc: 'Liquid Glass · 流体morphing玻璃质感',
        source: '#14',
        tokens: {
            pageBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
            fontFamily: "'Inter', sans-serif",
            cardBg: 'rgba(255, 255, 255, 0.15)',
            cardBorderColor: 'rgba(255, 255, 255, 0.35)',
            cardBorderWidth: '1px',
            cardRadius: '30px',
            cardShadow: 'none',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.75)',
            itemBg: 'rgba(255, 255, 255, 0.15)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.65)',
            itemBorderColor: 'rgba(255, 255, 255, 0.3)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '20px',
            upColor: '#FF7A9E',
            downColor: '#5EEAD4',
            btnBg: 'rgba(255, 255, 255, 0.2)',
            btnColor: '#ffffff',
            btnRadius: '999px',
            btnBorderColor: 'rgba(255, 255, 255, 0.4)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            tagBg: 'rgba(255, 255, 255, 0.15)',
            tagColor: '#ffffff',
            tagBorderColor: 'rgba(255, 255, 255, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'glassmorphism',
        name: '玻璃拟态',
        desc: 'Glassmorphism · 磨砂玻璃层次',
        source: '#03',
        tokens: {
            pageBg: 'linear-gradient(135deg, #0080FF 0%, #8B00FF 50%, #FF1493 100%)',
            fontFamily: "'Inter', sans-serif",
            cardBg: 'rgba(255, 255, 255, 0.15)',
            cardBorderColor: 'rgba(255, 255, 255, 0.25)',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: 'none',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.7)',
            itemBg: 'rgba(255, 255, 255, 0.18)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.6)',
            itemBorderColor: 'rgba(255, 255, 255, 0.22)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#FF8FB3',
            downColor: '#4FE3C1',
            btnBg: 'rgba(255, 255, 255, 0.25)',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: 'rgba(255, 255, 255, 0.35)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            tagBg: 'rgba(255, 255, 255, 0.18)',
            tagColor: '#ffffff',
            tagBorderColor: 'rgba(255, 255, 255, 0.25)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '10px',
        },
    },
    {
        id: 'vibrant-block',
        name: '活力色块',
        desc: 'Vibrant Block · 霓虹撞色大色块',
        source: '#06',
        tokens: {
            pageBg: '#000000',
            fontFamily: "'Space Grotesk', sans-serif",
            numberFontFamily: "'Space Grotesk', 'SF Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.06)',
            cardBorderColor: 'rgba(255, 255, 255, 0.14)',
            cardBorderWidth: '1px',
            cardRadius: '24px',
            cardShadow: 'none',
            titleColor: '#FFFFFF',
            descColor: 'rgba(255, 255, 255, 0.65)',
            itemBg: 'rgba(255, 255, 255, 0.08)',
            itemTitleColor: '#FFFFFF',
            itemDescColor: 'rgba(255, 255, 255, 0.55)',
            itemBorderColor: 'rgba(255, 255, 255, 0.16)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '14px',
            upColor: '#FF3355',
            downColor: '#39FF14',
            btnBg: '#39FF14',
            btnColor: '#000000',
            btnRadius: '12px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0px',
            tagBg: '#BF00FF',
            tagColor: '#FFFFFF',
            tagBorderColor: 'transparent',
            tagBorderStyle: 'solid',
            tagBorderWidth: '0px',
            tagRadius: '10px',
        },
    },
    {
        id: 'aurora',
        name: '极光渐变',
        desc: 'Aurora UI · 北极光流动渐变',
        source: '#10',
        tokens: {
            pageBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)',
            fontFamily: "'Inter', sans-serif",
            cardBg: 'rgba(255, 255, 255, 0.12)',
            cardBorderColor: 'rgba(255, 255, 255, 0.22)',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: 'none',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.8)',
            itemBg: 'rgba(255, 255, 255, 0.14)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.6)',
            itemBorderColor: 'rgba(255, 255, 255, 0.22)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '14px',
            // 涨跌色较最初版本加深，避免在渐变浅背景中对比度不足
            upColor: '#D6336C',
            downColor: '#0D9488',
            btnBg: 'linear-gradient(90deg, #3b82f6, #8b5cf6)',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: 'rgba(255, 255, 255, 0.25)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            tagBg: 'rgba(255, 255, 255, 0.16)',
            tagColor: '#ffffff',
            tagBorderColor: 'rgba(255, 255, 255, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'motion-driven',
        name: '动效驱动',
        desc: 'Motion-Driven · 深色科技动感',
        source: '#15',
        tokens: {
            pageBg: '#0F172A',
            fontFamily: "'Inter', sans-serif",
            cardBg: '#1E293B',
            cardBorderColor: '#334155',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: '0 10px 30px rgba(0, 0, 0, 0.35)',
            titleColor: '#F1F5F9',
            descColor: '#94A3B8',
            itemBg: 'rgba(148, 163, 184, 0.08)',
            itemTitleColor: '#F1F5F9',
            itemDescColor: '#94A3B8',
            itemBorderColor: '#334155',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#FB7185',
            downColor: '#34D399',
            btnBg: '#3B82F6',
            btnColor: '#FFFFFF',
            btnRadius: '10px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0px',
            tagBg: 'rgba(148, 163, 184, 0.15)',
            tagColor: '#E2E8F0',
            tagBorderColor: 'rgba(148, 163, 184, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'neubrutalism',
        name: '新粗野主义',
        desc: 'Neubrutalism · 硬阴影黑描边',
        source: '#38',
        tokens: {
            pageBg: '#FFF8E7',
            fontFamily: "'Space Grotesk', sans-serif",
            cardBg: '#FFFFFF',
            cardBorderColor: '#000000',
            cardBorderWidth: '4px',
            cardRadius: '0px',
            cardShadow: '6px 6px 0 0 #000000',
            titleColor: '#000000',
            descColor: '#1F2937',
            itemBg: '#FFFDF5',
            itemTitleColor: '#000000',
            itemDescColor: '#374151',
            itemBorderColor: '#000000',
            itemBorderStyle: 'solid',
            itemBorderWidth: '3px',
            itemRadius: '0px',
            upColor: '#FF3B30',
            downColor: '#10B981',
            btnBg: '#FF6B6B',
            btnColor: '#000000',
            btnRadius: '0px',
            btnBorderColor: '#000000',
            btnBorderStyle: 'solid',
            btnBorderWidth: '3px',
            btnShadow: '4px 4px 0 0 #000000',
            tagBg: '#FFE66D',
            tagColor: '#000000',
            tagBorderColor: '#000000',
            tagBorderStyle: 'solid',
            tagBorderWidth: '2px',
            tagRadius: '0px',
        },
    },
    {
        id: 'genz-chaos',
        name: 'Z世代混乱',
        desc: 'Gen Z Chaos · 倾斜贴纸涂鸦',
        source: '#57',
        tokens: {
            pageBg: '#1A1A2E',
            fontFamily: "'Clash Display', 'Space Grotesk', sans-serif",
            numberFontFamily: "'Space Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.06)',
            cardBorderColor: 'rgba(255, 255, 255, 0.16)',
            cardBorderWidth: '2px',
            cardRadius: '24px',
            cardShadow: 'none',
            titleColor: '#FFFFFF',
            descColor: 'rgba(255, 255, 255, 0.7)',
            itemBg: 'rgba(255, 255, 255, 0.08)',
            itemTitleColor: '#FFFFFF',
            itemDescColor: 'rgba(255, 255, 255, 0.6)',
            itemBorderColor: 'rgba(255, 255, 255, 0.3)',
            itemBorderStyle: 'dashed',
            itemBorderWidth: '2px',
            itemRadius: '20px',
            upColor: '#FF6B6B',
            downColor: '#4ECDC4',
            btnBg: '#FF6B6B',
            btnColor: '#FFFFFF',
            btnRadius: '999px',
            btnBorderColor: '#FF6B6B',
            btnBorderStyle: 'solid',
            btnBorderWidth: '2px',
            btnFontFamily: "'Space Mono', monospace",
            btnShadow: '3px 3px 0 rgba(0, 0, 0, 0.3)',
            tagBg: '#FFE66D',
            tagColor: '#000000',
            tagFontFamily: "'Space Mono', monospace",
            tagBorderColor: 'transparent',
            tagBorderStyle: 'solid',
            tagBorderWidth: '0px',
            tagRadius: '999px',
        },
    },
    {
        id: 'soft-ui-neu',
        name: '柔光新拟态',
        desc: 'Soft UI · 凸面双影浮雕',
        source: '自定义',
        tokens: {
            pageBg: '#dde1e7',
            fontFamily: "'Albert Sans', -apple-system, 'PingFang SC', sans-serif",
            numberFontFamily: "'Fragment Mono', 'SF Mono', monospace",
            cardBg: '#dde1e7',
            cardBorderColor: '#dde1e7',
            cardBorderWidth: '1px',
            cardRadius: '20px',
            cardShadow: '8px 8px 20px rgba(0, 0, 0, 0.07), -8px -8px 20px rgba(255, 255, 255, 0.9)',
            titleColor: '#334155',
            descColor: '#7c8aa0',
            itemBg: '#dde1e7',
            itemTitleColor: '#334155',
            itemDescColor: '#8b99ae',
            itemBorderColor: '#dde1e7',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#e11d48',
            downColor: '#0d9488',
            btnBg: '#6366f1',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: '#6366f1',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            btnShadow: '6px 6px 14px rgba(99, 102, 241, 0.35), -4px -4px 10px rgba(255, 255, 255, 0.8)',
            tagBg: '#dde1e7',
            tagColor: '#6366f1',
            tagFontFamily: "'Fragment Mono', monospace",
            tagBorderColor: '#dde1e7',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '10px',
        },
    },
    {
        id: 'y2k',
        name: '千禧霓虹',
        desc: 'Y2K · 全息渐变复古未来',
        source: '自定义',
        tokens: {
            pageBg: 'linear-gradient(160deg, #12081f 0%, #26064d 100%)',
            fontFamily: "'Albert Sans', -apple-system, 'PingFang SC', sans-serif",
            numberFontFamily: "'Fragment Mono', 'SF Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.07)',
            cardBorderColor: 'rgba(0, 255, 255, 0.35)',
            cardBorderWidth: '1px',
            cardRadius: '18px',
            cardShadow: '0 0 22px rgba(255, 0, 255, 0.15), inset 0 0 18px rgba(0, 255, 255, 0.06)',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.65)',
            itemBg: 'rgba(255, 255, 255, 0.08)',
            itemTitleColor: '#e9fbff',
            itemDescColor: 'rgba(255, 255, 255, 0.55)',
            itemBorderColor: 'rgba(0, 255, 255, 0.3)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#ff69b4',
            downColor: '#00ffff',
            btnBg: 'linear-gradient(90deg, #ff00ff, #7c3aed)',
            btnColor: '#ffffff',
            btnRadius: '999px',
            btnBorderColor: 'rgba(255, 255, 255, 0.6)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            btnFontFamily: "'Fragment Mono', monospace",
            btnShadow: '0 0 16px rgba(255, 0, 255, 0.5)',
            tagBg: 'rgba(0, 255, 255, 0.15)',
            tagColor: '#00ffff',
            tagFontFamily: "'Fragment Mono', monospace",
            tagBorderColor: 'rgba(0, 255, 255, 0.5)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        "id": "modern-gradient",
        "name": "现代渐变风",
        "desc": "Modern Gradient · 多彩玻璃态与动态光影",
        "source": "/styles/modern-gradient",
        "tokens": {
            "pageBg": "linear-gradient(135deg, #020617 0%, #1e1b4b 100%)",
            "fontFamily": "'Inter', -apple-system, 'PingFang SC', sans-serif",
            "numberFontFamily": "'JetBrains Mono', 'SF Mono', monospace",
            "cardBg": "rgba(255, 255, 255, 0.1)",
            "cardBorderColor": "rgba(255, 255, 255, 0.2)",
            "cardBorderWidth": "1px",
            "cardRadius": "24px",
            "cardShadow": "0 20px 25px -5px rgba(139, 92, 246, 0.25), 0 8px 10px -6px rgba(139, 92, 246, 0.1)",
            "titleColor": "#ffffff",
            "descColor": "rgba(255, 255, 255, 0.8)",
            "itemBg": "rgba(255, 255, 255, 0.05)",
            "itemTitleColor": "#ffffff",
            "itemDescColor": "rgba(255, 255, 255, 0.6)",
            "itemBorderColor": "rgba(255, 255, 255, 0.1)",
            "itemBorderStyle": "solid",
            "itemBorderWidth": "1px",
            "itemRadius": "16px",
            "upColor": "#d946ef",
            "downColor": "#06b6d4",
            "btnBg": "linear-gradient(90deg, #7c3aed, #db2777)",
            "btnColor": "#ffffff",
            "btnRadius": "16px",
            "btnBorderColor": "transparent",
            "btnBorderStyle": "solid",
            "btnBorderWidth": "0px",
            "btnFontFamily": "'Inter', sans-serif",
            "btnShadow": "0 10px 15px -3px rgba(124, 58, 237, 0.4), 0 4px 6px -4px rgba(124, 58, 237, 0.2)",
            "tagBg": "rgba(139, 92, 246, 0.2)",
            "tagColor": "#e879f9",
            "tagFontFamily": "'Inter', sans-serif",
            "tagBorderColor": "rgba(139, 92, 246, 0.3)",
            "tagBorderStyle": "solid",
            "tagBorderWidth": "1px",
            "tagRadius": "999px"
        },
    },
{
  "id": "memphis",
  "name": "孟菲斯风格",
  "desc": "Memphis · 大胆撞色与几何游乐场",
  "source": "/styles/memphis",
  "tokens": {
    "pageBg": "#fef9ef",
    "fontFamily": "'Space Grotesk', 'Arial Black', sans-serif",
    "numberFontFamily": "'Courier Prime', 'Courier New', monospace",
    "cardBg": "#ffffff",
    "cardBorderColor": "#000000",
    "cardBorderWidth": "4px",
    "cardRadius": "0px",
    "cardShadow": "5px 5px 0px 0px rgba(0,0,0,1)",
    "titleColor": "#000000",
    "descColor": "#2d3436",
    "itemBg": "#feca57",
    "itemTitleColor": "#000000",
    "itemDescColor": "#000000",
    "itemBorderColor": "#000000",
    "itemBorderStyle": "solid",
    "itemBorderWidth": "4px",
    "itemRadius": "0px",
    "upColor": "#1dd1a1",
    "downColor": "#ff6b6b",
    "btnBg": "#ff6b6b",
    "btnColor": "#000000",
    "btnRadius": "0px",
    "btnBorderColor": "#000000",
    "btnBorderStyle": "solid",
    "btnBorderWidth": "4px",
    "btnFontFamily": "'Space Grotesk', sans-serif",
    "btnShadow": "5px 5px 0px 0px rgba(0,0,0,1)",
    "tagBg": "#48dbfb",
    "tagColor": "#000000",
    "tagFontFamily": "'Space Grotesk', sans-serif",
    "tagBorderColor": "#000000",
    "tagBorderStyle": "solid",
    "tagBorderWidth": "4px",
    "tagRadius": "0px"
  }
},
{
    id: 'soft-ui',
    name: '柔和界面风',
    desc: 'Soft UI · 柔和圆润友好界面',
    source: 'STYLEKIT_STYLE_REFERENCE',
    tokens: {
        pageBg: 'linear-gradient(160deg, #f8fafc 0%, #eef2ff 100%)',
        fontFamily: "'Nunito Sans', -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif",
        numberFontFamily: "'IBM Plex Mono', 'SF Mono', monospace",
        cardBg: '#ffffff',
        cardBorderColor: 'transparent',
        cardBorderWidth: '0',
        cardRadius: '24px',
        cardShadow: '0 20px 25px -5px rgba(226, 232, 240, 0.5), 0 8px 10px -6px rgba(226, 232, 240, 0.5)',
        titleColor: '#1f2937',
        descColor: '#6b7280',
        itemBg: '#f9fafb',
        itemTitleColor: '#1f2937',
        itemDescColor: '#6b7280',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0',
        itemRadius: '16px',
        upColor: '#059669',
        downColor: '#db2777',
        btnBg: '#4f46e5',
        btnColor: '#ffffff',
        btnRadius: '16px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0',
        btnFontFamily: "'Nunito Sans', -apple-system, 'PingFang SC', sans-serif",
        btnShadow: '0 10px 15px -3px rgba(79, 70, 229, 0.3), 0 4px 6px -4px rgba(79, 70, 229, 0.3)',
        tagBg: 'rgba(99, 102, 241, 0.1)',
        tagColor: '#4f46e5',
        tagFontFamily: "'Nunito Sans', -apple-system, 'PingFang SC', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0',
        tagRadius: '999px',
    },
},
{
  "id": "neon-gradient",
  "name": "霓虹渐变",
  "desc": "Neon Gradient · 深色画布与高饱和发光渐变",
  "source": "/styles/neon-gradient",
  "tokens": {
    "pageBg": "#0f0a1e",
    "fontFamily": "'Outfit', 'Segoe UI', sans-serif",
    "numberFontFamily": "'Fira Code', monospace",
    "cardBg": "linear-gradient(135deg, #a855f7, #ec4899)",
    "cardBorderColor": "#fbbf24",
    "cardBorderWidth": "4px",
    "cardRadius": "24px",
    "cardShadow": "0 0 30px rgba(168, 85, 247, 0.4)",
    "titleColor": "#ffffff",
    "descColor": "rgba(255, 255, 255, 0.8)",
    "itemBg": "rgba(255, 255, 255, 0.05)",
    "itemTitleColor": "#ffffff",
    "itemDescColor": "rgba(255, 255, 255, 0.7)",
    "itemBorderColor": "rgba(168, 85, 247, 0.5)",
    "itemBorderStyle": "solid",
    "itemBorderWidth": "2px",
    "itemRadius": "16px",
    "upColor": "#a3e635",
    "downColor": "#fb7185",
    "btnBg": "linear-gradient(90deg, #22d3ee, #ec4899)",
    "btnColor": "#ffffff",
    "btnRadius": "16px",
    "btnBorderColor": "rgba(255, 255, 255, 0.2)",
    "btnBorderStyle": "solid",
    "btnBorderWidth": "2px",
    "btnFontFamily": "'Outfit', sans-serif",
    "btnShadow": "0 0 20px rgba(236, 72, 153, 0.5)",
    "tagBg": "rgba(34, 211, 238, 0.15)",
    "tagColor": "#22d3ee",
    "tagFontFamily": "'Outfit', sans-serif",
    "tagBorderColor": "rgba(34, 211, 238, 0.4)",
    "tagBorderStyle": "solid",
    "tagBorderWidth": "1px",
    "tagRadius": "999px"
  }
},
{
  "id": "liquid-glass2",
  "name": "Apple 流动玻璃",
  "desc": "Liquid Glass · WWDC25 霓虹描边与流体折射",
  "source": "/styles/liquid-glass",
  "tokens": {
    "pageBg": "#0f0f23",
    "fontFamily": "'SF Pro Display', -apple-system, 'PingFang SC', sans-serif",
    "numberFontFamily": "'SF Mono', 'Menlo', monospace",
    "cardBg": "rgba(255, 255, 255, 0.1)",
    "cardBorderColor": "rgba(255, 255, 255, 0.2)",
    "cardBorderWidth": "1px",
    "cardRadius": "24px",
    "cardShadow": "0 20px 40px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.4)",
    "titleColor": "#ffffff",
    "descColor": "rgba(255, 255, 255, 0.8)",
    "itemBg": "rgba(255, 255, 255, 0.08)",
    "itemTitleColor": "#ffffff",
    "itemDescColor": "rgba(255, 255, 255, 0.7)",
    "itemBorderColor": "rgba(255, 255, 255, 0.15)",
    "itemBorderStyle": "solid",
    "itemBorderWidth": "1px",
    "itemRadius": "16px",
    "upColor": "#4ecdc4",
    "downColor": "#ff2d92",
    "btnBg": "linear-gradient(90deg, #ff2d92, #a855f7)",
    "btnColor": "#ffffff",
    "btnRadius": "20px",
    "btnBorderColor": "rgba(255, 255, 255, 0.2)",
    "btnBorderStyle": "solid",
    "btnBorderWidth": "1px",
    "btnFontFamily": "'SF Pro Display', sans-serif",
    "btnShadow": "0 0 20px rgba(168, 85, 247, 0.3)",
    "tagBg": "rgba(78, 205, 196, 0.15)",
    "tagColor": "#4ecdc4",
    "tagFontFamily": "'SF Pro Display', sans-serif",
    "tagBorderColor": "rgba(78, 205, 196, 0.3)",
    "tagBorderStyle": "solid",
    "tagBorderWidth": "1px",
    "tagRadius": "999px"
  }
},
{
  "id": "holographic",
  "name": "全息渐变",
  "desc": "Holographic · 棱镜折射与宇宙深空虹彩",
  "source": "/styles/holographic",
  "tokens": {
    "pageBg": "#0a0a1f",
    "fontFamily": "'Space Grotesk', 'Inter', sans-serif",
    "numberFontFamily": "'JetBrains Mono', monospace",
    "cardBg": "rgba(255, 255, 255, 0.05)",
    "cardBorderColor": "rgba(255, 255, 255, 0.1)",
    "cardBorderWidth": "1px",
    "cardRadius": "16px",
    "cardShadow": "0 0 20px rgba(147, 51, 234, 0.2)",
    "titleColor": "#ffffff",
    "descColor": "rgba(255, 255, 255, 0.7)",
    "itemBg": "rgba(255, 255, 255, 0.03)",
    "itemTitleColor": "#ffffff",
    "itemDescColor": "rgba(255, 255, 255, 0.6)",
    "itemBorderColor": "rgba(255, 255, 255, 0.08)",
    "itemBorderStyle": "solid",
    "itemBorderWidth": "1px",
    "itemRadius": "12px",
    "upColor": "#00ff88",
    "downColor": "#ff0080",
    "btnBg": "linear-gradient(90deg, #ff0080, #7928ca, #00d4ff)",
    "btnColor": "#ffffff",
    "btnRadius": "12px",
    "btnBorderColor": "transparent",
    "btnBorderStyle": "solid",
    "btnBorderWidth": "0px",
    "btnFontFamily": "'Space Grotesk', sans-serif",
    "btnShadow": "0 0 25px rgba(147, 51, 234, 0.4)",
    "tagBg": "linear-gradient(135deg, rgba(255,0,128,0.2), rgba(0,212,255,0.2))",
    "tagColor": "#00d4ff",
    "tagFontFamily": "'Space Grotesk', sans-serif",
    "tagBorderColor": "rgba(255, 255, 255, 0.15)",
    "tagBorderStyle": "solid",
    "tagBorderWidth": "1px",
    "tagRadius": "999px"
  }
},
{
    id: 'maximalism',
    name: '极繁主义',
    desc: 'Maximalism · 饱和撞色与多重装饰',
    source: '自定义',
    tokens: {
        pageBg: '#1a0a2e',
        fontFamily: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
        numberFontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
        cardBg: '#1a0a2e',
        cardBorderColor: '#d4145a',
        cardBorderWidth: '4px',
        cardRadius: '4px',
        cardShadow: '4px 4px 0px #ffbe0b, 8px 8px 0px #3a86ff',
        titleColor: '#ffffff',
        descColor: 'rgba(131, 56, 236, 0.7)',
        itemBg: '#1a0a2e',
        itemTitleColor: '#ffffff',
        itemDescColor: '#ffbe0b',
        itemBorderColor: '#8338ec',
        itemBorderStyle: 'dashed',
        itemBorderWidth: '3px',
        itemRadius: '4px',
        upColor: '#06d6a0',
        downColor: '#d4145a',
        btnBg: '#d4145a', // 去掉了渐变叠加，改用纯粹的热粉色饱和撞色，减少过度重叠感
        btnColor: '#ffffff',
        btnRadius: '4px',
        btnBorderColor: '#ffbe0b',
        btnBorderStyle: 'solid',
        btnBorderWidth: '2px',
        btnFontFamily: "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
        btnShadow: '4px 4px 0px #ffbe0b, 8px 8px 0px #3a86ff',
        tagBg: 'transparent',
        tagColor: '#06d6a0',
        tagFontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
        tagBorderColor: '#06d6a0',
        tagBorderStyle: 'solid',
        tagBorderWidth: '4px',
        tagRadius: '4px',
    },
},
{
    id: 'dopamine',
    name: '多巴胺设计',
    desc: 'Dopamine Design · 高饱和霓虹与愉悦能量',
    source: '自定义',
    tokens: {
        pageBg: 'linear-gradient(135deg, #fff0f6 0%, #f3e8ff 50%, #e6f0ff 100%)',
        fontFamily: "'Inter', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif",
        numberFontFamily: "'Inter', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif",
        cardBg: '#ffffff',
        cardBorderColor: 'rgba(255, 0, 110, 0.2)',
        cardBorderWidth: '2px',
        cardRadius: '24px',
        cardShadow: '0 8px 30px rgba(255, 0, 110, 0.25)',
        titleColor: '#1a1a2e',
        descColor: 'rgba(26, 26, 46, 0.7)',
        itemBg: '#f8f0ff',
        itemTitleColor: '#1a1a2e',
        itemDescColor: 'rgba(26, 26, 46, 0.65)',
        itemBorderColor: 'rgba(131, 56, 236, 0.2)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '2px',
        itemRadius: '16px',
        upColor: '#06d6a0',
        downColor: '#ff006e',
        btnBg: '#8338ec',
        btnColor: '#ffffff',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        btnShadow: '0 8px 30px rgba(255, 0, 110, 0.4)',
        tagBg: 'rgba(255, 190, 11, 0.25)',
        tagColor: '#1a1a2e',
        tagFontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '999px',
    },
},
{
    id: 'shader-gradient',
    name: '着色器渐变',
    desc: 'Shader Gradient · 实时 WebGL 流动与冻毛玻璃',
    source: '自定义',
    tokens: {
        pageBg: '#08090D',
        fontFamily: "'Inter', system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
        numberFontFamily: "'JetBrains Mono', monospace",
        cardBg: 'rgba(255, 255, 255, 0.06)',
        cardBorderColor: 'rgba(255, 255, 255, 0.1)',
        cardBorderWidth: '1px',
        cardRadius: '16px',
        cardShadow: '0 20px 60px rgba(0, 0, 0, 0.45)',
        titleColor: '#ffffff',
        descColor: 'rgba(255, 255, 255, 0.7)',
        itemBg: 'rgba(255, 255, 255, 0.04)',
        itemTitleColor: '#ffffff',
        itemDescColor: 'rgba(255, 255, 255, 0.5)',
        itemBorderColor: 'rgba(255, 255, 255, 0.08)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '12px',
        upColor: '#22D3EE',
        downColor: '#F472B6',
        btnBg: '#7C5CFF',
        btnColor: '#ffffff',
        btnRadius: '12px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', system-ui, sans-serif",
        btnShadow: '0 4px 20px rgba(124, 92, 255, 0.35)',
        tagBg: 'rgba(124, 92, 255, 0.15)',
        tagColor: '#7C5CFF',
        tagFontFamily: "'JetBrains Mono', monospace",
        tagBorderColor: 'rgba(124, 92, 255, 0.3)',
        tagBorderStyle: 'solid',
        tagBorderWidth: '1px',
        tagRadius: '999px',
    },
},
{
    id: 'pastel-ui',
    name: '粉彩应用风',
    desc: 'Pastel App UI · 暖奶油底色与温润粉彩',
    source: '自定义',
    tokens: {
        pageBg: '#fff8f0',
        fontFamily: "'Inter', system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
        numberFontFamily: "'JetBrains Mono', monospace",
        cardBg: 'rgba(255, 255, 255, 0.8)',
        cardBorderColor: '#66508f',
        cardBorderWidth: '1px',
        cardRadius: '24px',
        cardShadow: '0 8px 24px rgba(102, 80, 143, 0.08)',
        titleColor: '#66508f',
        descColor: '#332d3d',
        itemBg: '#d9c7ff',
        itemTitleColor: '#66508f',
        itemDescColor: '#332d3d',
        itemBorderColor: '#66508f',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '16px',
        upColor: '#f64825ff',
        downColor: '#cbefdf',
        btnBg: '#66508f',
        btnColor: '#ffffff',
        btnRadius: '8px',
        btnBorderColor: '#66508f',
        btnBorderStyle: 'solid',
        btnBorderWidth: '1px',
        btnFontFamily: "'Inter', system-ui, sans-serif",
        btnShadow: '0 4px 12px rgba(102, 80, 143, 0.15)',
        tagBg: '#ffe49a',
        tagColor: '#66508f',
        tagFontFamily: "'JetBrains Mono', monospace",
        tagBorderColor: '#66508f',
        tagBorderStyle: 'solid',
        tagBorderWidth: '1px',
        tagRadius: '999px',
    },
}

];

// 根据 id 获取主题包；'' / undefined / 'default' 返回 null（默认样式）
export const getThemePack = (id) => {
    if (!id || id === 'default') return null;
    return THEME_PACKS.find(p => p.id === id) || null;
};

// 将主题包 token 转为 CSS 变量 style 对象（用于 React style / 挂到容器上）
export const buildPackVars = (pack) => {
    if (!pack?.tokens) return undefined;
    const t = pack.tokens;
    const vars = {};
    Object.entries(TOKEN_TO_VAR).forEach(([key, varName]) => {
        const val = t[key];
        if (val !== undefined && val !== null && val !== '') {
            vars[varName] = val;
        }
    });
    // 派生涨跌标签底色（半透明）
    if (!vars['--dp-up-bg'] && t.upColor) vars['--dp-up-bg'] = hexToRgba(t.upColor, 0.14);
    if (!vars['--dp-down-bg'] && t.downColor) vars['--dp-down-bg'] = hexToRgba(t.downColor, 0.14);
    return vars;
};
