// 主题包（Theme Pack）定义：从 uitest/styles 下的 12 个风格页面提取的配色与样式 token
// 每个 token 均为可选；未设置的 token 表示该项保持 CSS 默认样式
// 主题包通过 CSS 变量 + .dingpan-container.pack-active 覆盖层生效，
// 只影响盯盘页最外层组件（卡片/子项/按钮/标签），弹窗与 Tooltip 由 antd Portal
// 渲染在 body 下，天然不受影响

export const THEME_PACK_TOKEN_KEYS = [
    'pageBg',            // 页面背景颜色（支持渐变）
    'fontFamily',        // 全局字体 family
    'numberFontFamily',  // 数字字体 family
    // 容器卡片
    'cardBg',            // 容器卡片背景
    'cardBorderColor',   // 容器卡片边框颜色
    'cardBorderWidth',   // 容器卡片边框粗细
    'cardRadius',        // 容器卡片圆角
    'cardShadow',        // 容器卡片阴影
    // 标题/描述
    'titleColor',        // 标题字体颜色
    'descColor',         // 描述字体颜色
    // 子 item
    'itemBg',            // 子 item 背景色
    'itemTitleColor',    // 子 item 标题颜色
    'itemDescColor',     // 子 item 描述字体颜色
    'itemBorderColor',   // 子 item 边框颜色
    'itemBorderStyle',   // 子 item 边框样式（solid/dashed/dotted）
    'itemBorderWidth',   // 子 item 边框粗细
    'itemRadius',        // 子 item 圆角
    // 涨跌
    'upColor',           // 涨幅红色
    'downColor',         // 跌幅绿色
    'upBg',              // 涨幅标签底色（可选，默认由 upColor 派生）
    'downBg',            // 跌幅标签底色（可选，默认由 downColor 派生）
    // 按钮
    'btnBg',             // 按钮背景
    'btnColor',          // 按钮字体颜色
    'btnFontFamily',     // 按钮字体 family
    'btnRadius',         // 按钮圆角
    'btnBorderColor',    // 按钮边框颜色
    'btnBorderStyle',    // 按钮边框样式
    'btnBorderWidth',    // 按钮边框粗细
    'btnShadow',         // 按钮阴影
    // 标签 Tag
    'tagBg',             // tag 背景颜色
    'tagColor',          // tag 字体颜色
    'tagFontFamily',     // tag 字体 family
    'tagBorderColor',    // tag 边框颜色
    'tagBorderStyle',    // tag 边框样式
    'tagBorderWidth',    // tag 边框粗细
    'tagRadius',         // tag 圆角
];

// token -> CSS 变量名映射
const TOKEN_TO_VAR = {
    pageBg: '--dp-page-bg',
    fontFamily: '--dp-font-family',
    numberFontFamily: '--dp-number-font-family',
    cardBg: '--dp-card-bg',
    cardBorderColor: '--dp-card-border-color',
    cardBorderWidth: '--dp-card-border-width',
    cardRadius: '--dp-card-radius',
    cardShadow: '--dp-card-shadow',
    titleColor: '--dp-title-color',
    descColor: '--dp-desc-color',
    itemBg: '--dp-item-bg',
    itemTitleColor: '--dp-item-title-color',
    itemDescColor: '--dp-item-desc-color',
    itemBorderColor: '--dp-item-border-color',
    itemBorderStyle: '--dp-item-border-style',
    itemBorderWidth: '--dp-item-border-width',
    itemRadius: '--dp-item-radius',
    upColor: '--dp-up-color',
    downColor: '--dp-down-color',
    upBg: '--dp-up-bg',
    downBg: '--dp-down-bg',
    btnBg: '--dp-btn-bg',
    btnColor: '--dp-btn-color',
    btnFontFamily: '--dp-btn-font-family',
    btnRadius: '--dp-btn-radius',
    btnBorderColor: '--dp-btn-border-color',
    btnBorderStyle: '--dp-btn-border-style',
    btnBorderWidth: '--dp-btn-border-width',
    btnShadow: '--dp-btn-shadow',
    tagBg: '--dp-tag-bg',
    tagColor: '--dp-tag-color',
    tagFontFamily: '--dp-tag-font-family',
    tagBorderColor: '--dp-tag-border-color',
    tagBorderStyle: '--dp-tag-border-style',
    tagBorderWidth: '--dp-tag-border-width',
    tagRadius: '--dp-tag-radius',
};

// hex -> rgba（用于派生涨跌标签底色；非 hex 值返回中性半透明灰）
export const hexToRgba = (hex, alpha = 0.12) => {
    if (typeof hex === 'string' && /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(hex)) {
        let h = hex.slice(1);
        if (h.length === 3) h = h.split('').map(c => c + c).join('');
        const r = parseInt(h.slice(0, 2), 16);
        const g = parseInt(h.slice(2, 4), 16);
        const b = parseInt(h.slice(4, 6), 16);
        return `rgba(${r}, ${g}, ${b}, ${alpha})`;
    }
    return `rgba(127, 127, 127, ${alpha})`;
};

// 主题包列表（默认主题不在列表内，id 为 '' 表示默认/当前样式）
export const THEME_PACKS = [
    {
        id: 'liquid-glass',
        name: '流体玻璃',
        desc: 'Liquid Glass · 流体morphing玻璃质感',
        source: '#14',
        tokens: {
            pageBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
            fontFamily: "'Inter', sans-serif",
            cardBg: 'rgba(255, 255, 255, 0.15)',
            cardBorderColor: 'rgba(255, 255, 255, 0.35)',
            cardBorderWidth: '1px',
            cardRadius: '30px',
            cardShadow: 'none',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.75)',
            itemBg: 'rgba(255, 255, 255, 0.15)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.65)',
            itemBorderColor: 'rgba(255, 255, 255, 0.3)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '20px',
            upColor: '#f77598ff',
            downColor: '#5EEAD4',
            btnBg: 'rgba(255, 255, 255, 0.2)',
            btnColor: '#ffffff',
            btnRadius: '999px',
            btnBorderColor: 'rgba(255, 255, 255, 0.4)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            tagBg: 'rgba(255, 255, 255, 0.15)',
            tagColor: '#ffffff',
            tagBorderColor: 'rgba(255, 255, 255, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'glassmorphism',
        name: '玻璃拟态',
        desc: 'Glassmorphism · 磨砂玻璃层次',
        source: '#03',
        tokens: {
            pageBg: 'linear-gradient(135deg, #0080FF 0%, #8B00FF 50%, #FF1493 100%)',
            fontFamily: "'Inter', sans-serif",
            cardBg: 'rgba(255, 255, 255, 0.15)',
            cardBorderColor: 'rgba(255, 255, 255, 0.25)',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: 'none',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.7)',
            itemBg: 'rgba(255, 255, 255, 0.18)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.6)',
            itemBorderColor: 'rgba(255, 255, 255, 0.22)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#FF8FB3',
            downColor: '#4FE3C1',
            btnBg: 'rgba(255, 255, 255, 0.25)',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: 'rgba(255, 255, 255, 0.35)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            tagBg: 'rgba(255, 255, 255, 0.18)',
            tagColor: '#ffffff',
            tagBorderColor: 'rgba(255, 255, 255, 0.25)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '10px',
        },
    },
    {
        id: 'vibrant-block',
        name: '活力色块',
        desc: 'Vibrant Block · 霓虹撞色大色块',
        source: '#06',
        tokens: {
            pageBg: '#000000',
            fontFamily: "'Space Grotesk', sans-serif",
            numberFontFamily: "'Space Grotesk', 'SF Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.06)',
            cardBorderColor: 'rgba(255, 255, 255, 0.14)',
            cardBorderWidth: '1px',
            cardRadius: '24px',
            cardShadow: 'none',
            titleColor: '#FFFFFF',
            descColor: 'rgba(255, 255, 255, 0.65)',
            itemBg: 'rgba(255, 255, 255, 0.08)',
            itemTitleColor: '#FFFFFF',
            itemDescColor: 'rgba(255, 255, 255, 0.55)',
            itemBorderColor: 'rgba(255, 255, 255, 0.16)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '14px',
            upColor: '#FF3355',
            downColor: '#39FF14',
            btnBg: '#39FF14',
            btnColor: '#000000',
            btnRadius: '12px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0px',
            tagBg: '#BF00FF',
            tagColor: '#FFFFFF',
            tagBorderColor: 'transparent',
            tagBorderStyle: 'solid',
            tagBorderWidth: '0px',
            tagRadius: '10px',
        },
    },
    {
        id: 'aurora',
        name: '极光渐变',
        desc: 'Aurora UI · 北极光流动渐变',
        source: '#10',
        tokens: {
            pageBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)',
            fontFamily: "'Inter', sans-serif",
            cardBg: 'rgba(255, 255, 255, 0.12)',
            cardBorderColor: 'rgba(255, 255, 255, 0.22)',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: 'none',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.8)',
            itemBg: 'rgba(255, 255, 255, 0.14)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.6)',
            itemBorderColor: 'rgba(255, 255, 255, 0.22)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '14px',
            // 涨跌色较最初版本加深，避免在渐变浅背景中对比度不足
            upColor: '#D6336C',
            downColor: '#0D9488',
            btnBg: 'linear-gradient(90deg, #3b82f6, #8b5cf6)',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: 'rgba(255, 255, 255, 0.25)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            tagBg: 'rgba(255, 255, 255, 0.16)',
            tagColor: '#ffffff',
            tagBorderColor: 'rgba(255, 255, 255, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'motion-driven',
        name: '动效驱动',
        desc: 'Motion-Driven · 深色科技动感',
        source: '#15',
        tokens: {
            pageBg: '#0F172A',
            fontFamily: "'Inter', sans-serif",
            cardBg: '#1E293B',
            cardBorderColor: '#334155',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: '0 10px 30px rgba(0, 0, 0, 0.35)',
            titleColor: '#F1F5F9',
            descColor: '#94A3B8',
            itemBg: 'rgba(148, 163, 184, 0.08)',
            itemTitleColor: '#F1F5F9',
            itemDescColor: '#94A3B8',
            itemBorderColor: '#334155',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#FB7185',
            downColor: '#34D399',
            btnBg: '#3B82F6',
            btnColor: '#FFFFFF',
            btnRadius: '10px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0px',
            tagBg: 'rgba(148, 163, 184, 0.15)',
            tagColor: '#E2E8F0',
            tagBorderColor: 'rgba(148, 163, 184, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'neubrutalism',
        name: '新粗野主义',
        desc: 'Neubrutalism · 硬阴影黑描边',
        source: '#38',
        tokens: {
            pageBg: '#FFF8E7',
            fontFamily: "'Space Grotesk', sans-serif",
            cardBg: '#FFFFFF',
            cardBorderColor: '#000000',
            cardBorderWidth: '4px',
            cardRadius: '0px',
            cardShadow: '6px 6px 0 0 #000000',
            titleColor: '#000000',
            descColor: '#1F2937',
            itemBg: '#FFFDF5',
            itemTitleColor: '#000000',
            itemDescColor: '#374151',
            itemBorderColor: '#000000',
            itemBorderStyle: 'solid',
            itemBorderWidth: '3px',
            itemRadius: '0px',
            upColor: '#FF3B30',
            downColor: '#10B981',
            btnBg: '#FF6B6B',
            btnColor: '#000000',
            btnRadius: '0px',
            btnBorderColor: '#000000',
            btnBorderStyle: 'solid',
            btnBorderWidth: '3px',
            btnShadow: '4px 4px 0 0 #000000',
            tagBg: '#FFE66D',
            tagColor: '#000000',
            tagBorderColor: '#000000',
            tagBorderStyle: 'solid',
            tagBorderWidth: '2px',
            tagRadius: '0px',
        },
    },
    {
        id: 'genz-chaos',
        name: 'Z世代混乱',
        desc: 'Gen Z Chaos · 倾斜贴纸涂鸦',
        source: '#57',
        tokens: {
            pageBg: '#1A1A2E',
            fontFamily: "'Clash Display', 'Space Grotesk', sans-serif",
            numberFontFamily: "'Space Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.06)',
            cardBorderColor: 'rgba(255, 255, 255, 0.16)',
            cardBorderWidth: '2px',
            cardRadius: '24px',
            cardShadow: 'none',
            titleColor: '#FFFFFF',
            descColor: 'rgba(255, 255, 255, 0.7)',
            itemBg: 'rgba(255, 255, 255, 0.08)',
            itemTitleColor: '#FFFFFF',
            itemDescColor: 'rgba(255, 255, 255, 0.6)',
            itemBorderColor: 'rgba(255, 255, 255, 0.3)',
            itemBorderStyle: 'dashed',
            itemBorderWidth: '2px',
            itemRadius: '20px',
            upColor: '#FF6B6B',
            downColor: '#4ECDC4',
            btnBg: '#FF6B6B',
            btnColor: '#FFFFFF',
            btnRadius: '999px',
            btnBorderColor: '#FF6B6B',
            btnBorderStyle: 'solid',
            btnBorderWidth: '2px',
            btnFontFamily: "'Space Mono', monospace",
            btnShadow: '3px 3px 0 rgba(0, 0, 0, 0.3)',
            tagBg: '#FFE66D',
            tagColor: '#000000',
            tagFontFamily: "'Space Mono', monospace",
            tagBorderColor: 'transparent',
            tagBorderStyle: 'solid',
            tagBorderWidth: '0px',
            tagRadius: '999px',
        },
    },
    {
        id: 'soft-ui-neu',
        name: '柔光新拟态',
        desc: 'Soft UI · 凸面双影浮雕',
        source: '自定义',
        tokens: {
            pageBg: '#dde1e7',
            fontFamily: "'Albert Sans', -apple-system, 'PingFang SC', sans-serif",
            numberFontFamily: "'Fragment Mono', 'SF Mono', monospace",
            cardBg: '#dde1e7',
            cardBorderColor: '#dde1e7',
            cardBorderWidth: '1px',
            cardRadius: '20px',
            cardShadow: '8px 8px 20px rgba(0, 0, 0, 0.07), -8px -8px 20px rgba(255, 255, 255, 0.9)',
            titleColor: '#334155',
            descColor: '#7c8aa0',
            itemBg: '#dde1e7',
            itemTitleColor: '#334155',
            itemDescColor: '#8b99ae',
            itemBorderColor: '#dde1e7',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#e11d48',
            downColor: '#0d9488',
            btnBg: '#6366f1',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: '#6366f1',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            btnShadow: '6px 6px 14px rgba(99, 102, 241, 0.35), -4px -4px 10px rgba(255, 255, 255, 0.8)',
            tagBg: '#dde1e7',
            tagColor: '#6366f1',
            tagFontFamily: "'Fragment Mono', monospace",
            tagBorderColor: '#dde1e7',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '10px',
        },
    },
    {
        id: 'y2k',
        name: '千禧霓虹',
        desc: 'Y2K · 全息渐变复古未来',
        source: '自定义',
        tokens: {
            pageBg: 'linear-gradient(160deg, #12081f 0%, #26064d 100%)',
            fontFamily: "'Albert Sans', -apple-system, 'PingFang SC', sans-serif",
            numberFontFamily: "'Fragment Mono', 'SF Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.07)',
            cardBorderColor: 'rgba(0, 255, 255, 0.35)',
            cardBorderWidth: '1px',
            cardRadius: '18px',
            cardShadow: '0 0 22px rgba(255, 0, 255, 0.15), inset 0 0 18px rgba(0, 255, 255, 0.06)',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.65)',
            itemBg: 'rgba(255, 255, 255, 0.08)',
            itemTitleColor: '#e9fbff',
            itemDescColor: 'rgba(255, 255, 255, 0.55)',
            itemBorderColor: 'rgba(0, 255, 255, 0.3)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#ff69b4',
            downColor: '#00ffff',
            btnBg: 'linear-gradient(90deg, #ff00ff, #7c3aed)',
            btnColor: '#ffffff',
            btnRadius: '999px',
            btnBorderColor: 'rgba(255, 255, 255, 0.6)',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            btnFontFamily: "'Fragment Mono', monospace",
            btnShadow: '0 0 16px rgba(255, 0, 255, 0.5)',
            tagBg: 'rgba(0, 255, 255, 0.15)',
            tagColor: '#00ffff',
            tagFontFamily: "'Fragment Mono', monospace",
            tagBorderColor: 'rgba(0, 255, 255, 0.5)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        "id": "modern-gradient",
        "name": "现代渐变风",
        "desc": "Modern Gradient · 多彩玻璃态与动态光影",
        "source": "/styles/modern-gradient",
        "tokens": {
            "pageBg": "linear-gradient(135deg, #020617 0%, #1e1b4b 100%)",
            "fontFamily": "'Inter', -apple-system, 'PingFang SC', sans-serif",
            "numberFontFamily": "'JetBrains Mono', 'SF Mono', monospace",
            "cardBg": "rgba(255, 255, 255, 0.1)",
            "cardBorderColor": "rgba(255, 255, 255, 0.2)",
            "cardBorderWidth": "1px",
            "cardRadius": "24px",
            "cardShadow": "0 20px 25px -5px rgba(139, 92, 246, 0.25), 0 8px 10px -6px rgba(139, 92, 246, 0.1)",
            "titleColor": "#ffffff",
            "descColor": "rgba(255, 255, 255, 0.8)",
            "itemBg": "rgba(255, 255, 255, 0.05)",
            "itemTitleColor": "#ffffff",
            "itemDescColor": "rgba(255, 255, 255, 0.6)",
            "itemBorderColor": "rgba(255, 255, 255, 0.1)",
            "itemBorderStyle": "solid",
            "itemBorderWidth": "1px",
            "itemRadius": "16px",
            "upColor": "#d946ef",
            "downColor": "#06b6d4",
            "btnBg": "linear-gradient(90deg, #7c3aed, #db2777)",
            "btnColor": "#ffffff",
            "btnRadius": "16px",
            "btnBorderColor": "transparent",
            "btnBorderStyle": "solid",
            "btnBorderWidth": "0px",
            "btnFontFamily": "'Inter', sans-serif",
            "btnShadow": "0 10px 15px -3px rgba(124, 58, 237, 0.4), 0 4px 6px -4px rgba(124, 58, 237, 0.2)",
            "tagBg": "rgba(139, 92, 246, 0.2)",
            "tagColor": "#e879f9",
            "tagFontFamily": "'Inter', sans-serif",
            "tagBorderColor": "rgba(139, 92, 246, 0.3)",
            "tagBorderStyle": "solid",
            "tagBorderWidth": "1px",
            "tagRadius": "999px"
        },
    },
    {
        "id": "memphis",
        "name": "孟菲斯风格",
        "desc": "Memphis · 大胆撞色与几何游乐场",
        "source": "/styles/memphis",
        "tokens": {
            "pageBg": "#fef9ef",
            "fontFamily": "'Space Grotesk', 'Arial Black', sans-serif",
            "numberFontFamily": "'Courier Prime', 'Courier New', monospace",
            "cardBg": "#ffffff",
            "cardBorderColor": "#000000",
            "cardBorderWidth": "4px",
            "cardRadius": "0px",
            "cardShadow": "5px 5px 0px 0px rgba(0,0,0,1)",
            "titleColor": "#000000",
            "descColor": "#2d3436",
            "itemBg": "#feca57",
            "itemTitleColor": "#000000",
            "itemDescColor": "#000000",
            "itemBorderColor": "#000000",
            "itemBorderStyle": "solid",
            "itemBorderWidth": "4px",
            "itemRadius": "0px",
            "upColor": "#e815e5ff",
            "downColor": "#077c15ff",
            "btnBg": "#ff6b6b",
            "btnColor": "#000000",
            "btnRadius": "0px",
            "btnBorderColor": "#000000",
            "btnBorderStyle": "solid",
            "btnBorderWidth": "4px",
            "btnFontFamily": "'Space Grotesk', sans-serif",
            "btnShadow": "5px 5px 0px 0px rgba(0,0,0,1)",
            "tagBg": "#48dbfb",
            "tagColor": "#000000",
            "tagFontFamily": "'Space Grotesk', sans-serif",
            "tagBorderColor": "#000000",
            "tagBorderStyle": "solid",
            "tagBorderWidth": "4px",
            "tagRadius": "0px"
        }
    },
    {
        id: 'soft-ui',
        name: '柔和界面风',
        desc: 'Soft UI · 柔和圆润友好界面',
        source: 'STYLEKIT_STYLE_REFERENCE',
        tokens: {
            pageBg: 'linear-gradient(160deg, #f8fafc 0%, #eef2ff 100%)',
            fontFamily: "'Nunito Sans', -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif",
            numberFontFamily: "'IBM Plex Mono', 'SF Mono', monospace",
            cardBg: '#ffffff',
            cardBorderColor: 'transparent',
            cardBorderWidth: '0',
            cardRadius: '24px',
            cardShadow: '0 20px 25px -5px rgba(226, 232, 240, 0.5), 0 8px 10px -6px rgba(226, 232, 240, 0.5)',
            titleColor: '#1f2937',
            descColor: '#6b7280',
            itemBg: '#f9fafb',
            itemTitleColor: '#1f2937',
            itemDescColor: '#6b7280',
            itemBorderColor: 'transparent',
            itemBorderStyle: 'solid',
            itemBorderWidth: '0',
            itemRadius: '16px',
            upColor: '#059669',
            downColor: '#db2777',
            btnBg: '#4f46e5',
            btnColor: '#ffffff',
            btnRadius: '16px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0',
            btnFontFamily: "'Nunito Sans', -apple-system, 'PingFang SC', sans-serif",
            btnShadow: '0 10px 15px -3px rgba(79, 70, 229, 0.3), 0 4px 6px -4px rgba(79, 70, 229, 0.3)',
            tagBg: 'rgba(99, 102, 241, 0.1)',
            tagColor: '#4f46e5',
            tagFontFamily: "'Nunito Sans', -apple-system, 'PingFang SC', sans-serif",
            tagBorderColor: 'transparent',
            tagBorderStyle: 'solid',
            tagBorderWidth: '0',
            tagRadius: '999px',
        },
    },
    {
        "id": "neon-gradient",
        "name": "霓虹渐变",
        "desc": "Neon Gradient · 深色画布与高饱和发光渐变",
        "source": "/styles/neon-gradient",
        "tokens": {
            "pageBg": "#0f0a1e",
            "fontFamily": "'Outfit', 'Segoe UI', sans-serif",
            "numberFontFamily": "'Fira Code', monospace",
            "cardBg": "linear-gradient(135deg, #a855f7, #ec4899)",
            "cardBorderColor": "#fbbf24",
            "cardBorderWidth": "4px",
            "cardRadius": "24px",
            "cardShadow": "0 0 30px rgba(168, 85, 247, 0.4)",
            "titleColor": "#ffffff",
            "descColor": "rgba(255, 255, 255, 0.8)",
            "itemBg": "rgba(255, 255, 255, 0.05)",
            "itemTitleColor": "#ffffff",
            "itemDescColor": "rgba(255, 255, 255, 0.7)",
            "itemBorderColor": "rgba(168, 85, 247, 0.5)",
            "itemBorderStyle": "solid",
            "itemBorderWidth": "2px",
            "itemRadius": "16px",
            "upColor": "#fb7185",
            "downColor": "#a3e635",
            "btnBg": "linear-gradient(90deg, #22d3ee, #ec4899)",
            "btnColor": "#ffffff",
            "btnRadius": "16px",
            "btnBorderColor": "rgba(255, 255, 255, 0.2)",
            "btnBorderStyle": "solid",
            "btnBorderWidth": "2px",
            "btnFontFamily": "'Outfit', sans-serif",
            "btnShadow": "0 0 20px rgba(236, 72, 153, 0.5)",
            "tagBg": "rgba(34, 211, 238, 0.15)",
            "tagColor": "#22d3ee",
            "tagFontFamily": "'Outfit', sans-serif",
            "tagBorderColor": "rgba(34, 211, 238, 0.4)",
            "tagBorderStyle": "solid",
            "tagBorderWidth": "1px",
            "tagRadius": "999px"
        }
    },
    {
        "id": "liquid-glass2",
        "name": "Apple 流动玻璃",
        "desc": "Liquid Glass · WWDC25 霓虹描边与流体折射",
        "source": "/styles/liquid-glass",
        "tokens": {
            "pageBg": "#0f0f23",
            "fontFamily": "'SF Pro Display', -apple-system, 'PingFang SC', sans-serif",
            "numberFontFamily": "'SF Mono', 'Menlo', monospace",
            "cardBg": "rgba(255, 255, 255, 0.1)",
            "cardBorderColor": "rgba(255, 255, 255, 0.2)",
            "cardBorderWidth": "1px",
            "cardRadius": "24px",
            "cardShadow": "0 20px 40px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.4)",
            "titleColor": "#ffffff",
            "descColor": "rgba(255, 255, 255, 0.8)",
            "itemBg": "rgba(255, 255, 255, 0.08)",
            "itemTitleColor": "#ffffff",
            "itemDescColor": "rgba(255, 255, 255, 0.7)",
            "itemBorderColor": "rgba(255, 255, 255, 0.15)",
            "itemBorderStyle": "solid",
            "itemBorderWidth": "1px",
            "itemRadius": "16px",
            "upColor": "#4ecdc4",
            "downColor": "#ff2d92",
            "btnBg": "linear-gradient(90deg, #ff2d92, #a855f7)",
            "btnColor": "#ffffff",
            "btnRadius": "20px",
            "btnBorderColor": "rgba(255, 255, 255, 0.2)",
            "btnBorderStyle": "solid",
            "btnBorderWidth": "1px",
            "btnFontFamily": "'SF Pro Display', sans-serif",
            "btnShadow": "0 0 20px rgba(168, 85, 247, 0.3)",
            "tagBg": "rgba(78, 205, 196, 0.15)",
            "tagColor": "#4ecdc4",
            "tagFontFamily": "'SF Pro Display', sans-serif",
            "tagBorderColor": "rgba(78, 205, 196, 0.3)",
            "tagBorderStyle": "solid",
            "tagBorderWidth": "1px",
            "tagRadius": "999px"
        }
    },
    {
        "id": "holographic",
        "name": "全息渐变",
        "desc": "Holographic · 棱镜折射与宇宙深空虹彩",
        "source": "/styles/holographic",
        "tokens": {
            "pageBg": "#0a0a1f",
            "fontFamily": "'Space Grotesk', 'Inter', sans-serif",
            "numberFontFamily": "'JetBrains Mono', monospace",
            "cardBg": "rgba(255, 255, 255, 0.05)",
            "cardBorderColor": "rgba(255, 255, 255, 0.1)",
            "cardBorderWidth": "1px",
            "cardRadius": "16px",
            "cardShadow": "0 0 20px rgba(147, 51, 234, 0.2)",
            "titleColor": "#ffffff",
            "descColor": "rgba(255, 255, 255, 0.7)",
            "itemBg": "rgba(255, 255, 255, 0.03)",
            "itemTitleColor": "#ffffff",
            "itemDescColor": "rgba(255, 255, 255, 0.6)",
            "itemBorderColor": "rgba(255, 255, 255, 0.08)",
            "itemBorderStyle": "solid",
            "itemBorderWidth": "1px",
            "itemRadius": "12px",
            "upColor": "#00ff88",
            "downColor": "#ff0080",
            "btnBg": "linear-gradient(90deg, #ff0080, #7928ca, #00d4ff)",
            "btnColor": "#ffffff",
            "btnRadius": "12px",
            "btnBorderColor": "transparent",
            "btnBorderStyle": "solid",
            "btnBorderWidth": "0px",
            "btnFontFamily": "'Space Grotesk', sans-serif",
            "btnShadow": "0 0 25px rgba(147, 51, 234, 0.4)",
            "tagBg": "linear-gradient(135deg, rgba(255,0,128,0.2), rgba(0,212,255,0.2))",
            "tagColor": "#00d4ff",
            "tagFontFamily": "'Space Grotesk', sans-serif",
            "tagBorderColor": "rgba(255, 255, 255, 0.15)",
            "tagBorderStyle": "solid",
            "tagBorderWidth": "1px",
            "tagRadius": "999px"
        }
    },
    {
        id: 'maximalism',
        name: '极繁主义',
        desc: 'Maximalism · 饱和撞色与多重装饰',
        source: '自定义',
        tokens: {
            pageBg: '#1a0a2e',
            fontFamily: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
            numberFontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
            cardBg: '#1a0a2e',
            cardBorderColor: '#d4145a',
            cardBorderWidth: '4px',
            cardRadius: '4px',
            cardShadow: '4px 4px 0px #ffbe0b, 8px 8px 0px #3a86ff',
            titleColor: '#ffffff',
            descColor: 'rgba(131, 56, 236, 0.7)',
            itemBg: '#1a0a2e',
            itemTitleColor: '#ffffff',
            itemDescColor: '#ffbe0b',
            itemBorderColor: '#8338ec',
            itemBorderStyle: 'dashed',
            itemBorderWidth: '3px',
            itemRadius: '4px',
            upColor: '#d4145a',
            downColor: '#06d6a0',
            btnBg: '#d4145a', // 去掉了渐变叠加，改用纯粹的热粉色饱和撞色，减少过度重叠感
            btnColor: '#ffffff',
            btnRadius: '4px',
            btnBorderColor: '#ffbe0b',
            btnBorderStyle: 'solid',
            btnBorderWidth: '2px',
            btnFontFamily: "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
            btnShadow: '4px 4px 0px #ffbe0b, 8px 8px 0px #3a86ff',
            tagBg: 'transparent',
            tagColor: '#06d6a0',
            tagFontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
            tagBorderColor: '#06d6a0',
            tagBorderStyle: 'solid',
            tagBorderWidth: '4px',
            tagRadius: '4px',
        },
    },
    {
        id: 'dopamine',
        name: '多巴胺设计',
        desc: 'Dopamine Design · 高饱和霓虹与愉悦能量',
        source: '自定义',
        tokens: {
            pageBg: 'linear-gradient(135deg, #fff0f6 0%, #f3e8ff 50%, #e6f0ff 100%)',
            fontFamily: "'Inter', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif",
            numberFontFamily: "'Inter', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif",
            cardBg: '#ffffff',
            cardBorderColor: 'rgba(255, 0, 110, 0.2)',
            cardBorderWidth: '2px',
            cardRadius: '24px',
            cardShadow: '0 8px 30px rgba(255, 0, 110, 0.25)',
            titleColor: '#1a1a2e',
            descColor: 'rgba(26, 26, 46, 0.7)',
            itemBg: '#f8f0ff',
            itemTitleColor: '#1a1a2e',
            itemDescColor: 'rgba(26, 26, 46, 0.65)',
            itemBorderColor: 'rgba(131, 56, 236, 0.2)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '2px',
            itemRadius: '16px',
            upColor: '#06d6a0',
            downColor: '#ff006e',
            btnBg: '#8338ec',
            btnColor: '#ffffff',
            btnRadius: '999px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0px',
            btnFontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
            btnShadow: '0 8px 30px rgba(255, 0, 110, 0.4)',
            tagBg: 'rgba(255, 190, 11, 0.25)',
            tagColor: '#1a1a2e',
            tagFontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
            tagBorderColor: 'transparent',
            tagBorderStyle: 'solid',
            tagBorderWidth: '0px',
            tagRadius: '999px',
        },
    },
    {
        id: 'shader-gradient',
        name: '着色器渐变',
        desc: 'Shader Gradient · 实时 WebGL 流动与冻毛玻璃',
        source: '自定义',
        tokens: {
            pageBg: '#08090D',
            fontFamily: "'Inter', system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
            numberFontFamily: "'JetBrains Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.06)',
            cardBorderColor: 'rgba(255, 255, 255, 0.1)',
            cardBorderWidth: '1px',
            cardRadius: '16px',
            cardShadow: '0 20px 60px rgba(0, 0, 0, 0.45)',
            titleColor: '#ffffff',
            descColor: 'rgba(255, 255, 255, 0.7)',
            itemBg: 'rgba(255, 255, 255, 0.04)',
            itemTitleColor: '#ffffff',
            itemDescColor: 'rgba(255, 255, 255, 0.5)',
            itemBorderColor: 'rgba(255, 255, 255, 0.08)',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '12px',
            upColor: '#22D3EE',
            downColor: '#F472B6',
            btnBg: '#7C5CFF',
            btnColor: '#ffffff',
            btnRadius: '12px',
            btnBorderColor: 'transparent',
            btnBorderStyle: 'solid',
            btnBorderWidth: '0px',
            btnFontFamily: "'Inter', system-ui, sans-serif",
            btnShadow: '0 4px 20px rgba(124, 92, 255, 0.35)',
            tagBg: 'rgba(124, 92, 255, 0.15)',
            tagColor: '#7C5CFF',
            tagFontFamily: "'JetBrains Mono', monospace",
            tagBorderColor: 'rgba(124, 92, 255, 0.3)',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
        id: 'pastel-ui',
        name: '粉彩应用风',
        desc: 'Pastel App UI · 暖奶油底色与温润粉彩',
        source: '自定义',
        tokens: {
            pageBg: '#fff8f0',
            fontFamily: "'Inter', system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
            numberFontFamily: "'JetBrains Mono', monospace",
            cardBg: 'rgba(255, 255, 255, 0.8)',
            cardBorderColor: '#66508f',
            cardBorderWidth: '1px',
            cardRadius: '24px',
            cardShadow: '0 8px 24px rgba(102, 80, 143, 0.08)',
            titleColor: '#66508f',
            descColor: '#332d3d',
            itemBg: '#d9c7ff',
            itemTitleColor: '#66508f',
            itemDescColor: '#332d3d',
            itemBorderColor: '#66508f',
            itemBorderStyle: 'solid',
            itemBorderWidth: '1px',
            itemRadius: '16px',
            upColor: '#f64825ff',
            downColor: '#2d7553ff',
            btnBg: '#66508f',
            btnColor: '#ffffff',
            btnRadius: '8px',
            btnBorderColor: '#66508f',
            btnBorderStyle: 'solid',
            btnBorderWidth: '1px',
            btnFontFamily: "'Inter', system-ui, sans-serif",
            btnShadow: '0 4px 12px rgba(102, 80, 143, 0.15)',
            tagBg: '#ffe49a',
            tagColor: '#66508f',
            tagFontFamily: "'JetBrains Mono', monospace",
            tagBorderColor: '#66508f',
            tagBorderStyle: 'solid',
            tagBorderWidth: '1px',
            tagRadius: '999px',
        },
    },
    {
    id: 'neon-glass-dark',
    name: '霓虹玻璃暗夜',
    desc: 'Neon Glass Dark · 深色玻璃拟态与霓虹渐变',
    source: '#uploaded-image',
    tokens: {
        pageBg: '#0F172A',
        fontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        cardBg: 'rgba(30, 41, 59, 0.6)',
        cardBorderColor: 'rgba(255, 255, 255, 0.08)',
        cardBorderWidth: '1px',
        cardRadius: '16px',
        cardShadow: '0 8px 32px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        titleColor: '#FFFFFF',
        descColor: 'rgba(255, 255, 255, 0.65)',
        itemBg: 'rgba(255, 255, 255, 0.04)',
        itemTitleColor: '#F1F5F9',
        itemDescColor: 'rgba(255, 255, 255, 0.5)',
        itemBorderColor: 'rgba(255, 255, 255, 0.06)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '12px',
        upColor: '#00D2FF',
        downColor: '#FF6B9D',
        btnBg: 'linear-gradient(135deg, #6C5CE7 0%, #00D2FF 100%)',
        btnColor: '#FFFFFF',
        btnRadius: '12px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', sans-serif",
        btnShadow: '0 4px 15px rgba(108, 92, 231, 0.4)',
        tagBg: 'rgba(108, 92, 231, 0.15)',
        tagColor: '#A78BFA',
        tagFontFamily: "'Inter', sans-serif",
        tagBorderColor: 'rgba(108, 92, 231, 0.3)',
        tagBorderStyle: 'solid',
        tagBorderWidth: '1px',
        tagRadius: '8px',
    },
},
{
    id: 'pixel-flux-neon',
    name: '像素流彩霓虹',
    desc: 'Pixel Flux Neon · 噪点背景 + 像素化渐变爆炸效果',
    source: '#uploaded-image-3',
    tokens: {
        pageBg: '#0A0508', // 深紫黑带微噪点
        fontFamily: "'Inter', 'Satoshi', 'Helvetica Neue', sans-serif",
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        cardBg: 'rgba(20, 10, 25, 0.7)',
        cardBorderColor: 'rgba(255, 255, 255, 0.1)',
        cardBorderWidth: '1px',
        cardRadius: '16px',
        cardShadow: '0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        titleColor: '#FFFFFF',
        descColor: 'rgba(255, 255, 255, 0.6)',
        itemBg: 'rgba(255, 255, 255, 0.05)',
        itemTitleColor: '#FFFFFF',
        itemDescColor: 'rgba(255, 255, 255, 0.5)',
        itemBorderColor: 'rgba(255, 255, 255, 0.08)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '12px',
        upColor: '#FF00FF', // 荧光粉
        downColor: '#00FFFF', // 荧光青
        btnBg: 'linear-gradient(135deg, #FF00FF 0%, #00FFFF 50%, #FFD700 100%)',
        btnColor: '#000000',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Space Grotesk', 'Clash Display', sans-serif",
        btnShadow: '0 4px 20px rgba(255, 0, 255, 0.4)',
        tagBg: '#FF00FF',
        tagColor: '#FFFFFF',
        tagFontFamily: "'JetBrains Mono', monospace",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '6px',
        // 特有像素/噪点风格 Tokens
        pixelSize: '4px',
        noiseOpacity: '0.08',
        gradientColors: ['#FF00FF', '#00FFFF', '#FFD700', '#8A2BE2', '#FF4500'],
        accentGlow: '0 0 20px rgba(255, 0, 255, 0.6)',
    },
},
{
    id: 'vr-commerce-glow',
    name: 'VR商域光晕',
    desc: 'VR Commerce Glow · 深色沉浸 + 橙光产品轮廓 + AI助手交互',
    source: '#uploaded-image-5',
    tokens: {
        pageBg: '#0A0A0A',
        fontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        cardBg: 'rgba(20, 20, 20, 0.8)',
        cardBorderColor: 'rgba(255, 140, 0, 0.15)',
        cardBorderWidth: '1px',
        cardRadius: '20px',
        cardShadow: '0 8px 32px rgba(255, 140, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        titleColor: '#FFFFFF',
        descColor: 'rgba(255, 255, 255, 0.7)',
        itemBg: 'rgba(255, 255, 255, 0.06)',
        itemTitleColor: '#FFFFFF',
        itemDescColor: 'rgba(255, 255, 255, 0.5)',
        itemBorderColor: 'rgba(255, 140, 0, 0.2)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '16px',
        upColor: '#FF8C00', // 主品牌橙
        downColor: '#FF4500', // 深橙用于折扣/警告
        btnBg: '#FF8C00',
        btnColor: '#000000',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', sans-serif",
        btnShadow: '0 4px 20px rgba(255, 140, 0, 0.4)',
        tagBg: '#FF8C00',
        tagColor: '#000000',
        tagFontFamily: "'Inter', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '6px',
        // 特有产品光效 & AI 元素
        productGlowColor: '#FF8C00',
        productGlowBlur: '20px',
        aiAssistantBg: 'rgba(255, 140, 0, 0.1)',
        aiAssistantBorder: '1px solid rgba(255, 140, 0, 0.3)',
        aiAssistantRadius: '16px',
        searchInputBg: 'rgba(255, 255, 255, 0.08)',
        searchInputColor: '#FFFFFF',
        searchInputBorder: '1px solid rgba(255, 255, 255, 0.1)',
        navIconActive: '#FF8C00',
        navIconInactive: 'rgba(255, 255, 255, 0.4)',
        priceOriginalColor: 'rgba(255, 255, 255, 0.4)',
        priceDiscountColor: '#FF4500',
        ratingStarColor: '#FFD700',
    },
},
{
    id: 'onro-glass-dashboard',
    name: 'Onro玻璃仪表',
    desc: 'Onro Glass Dashboard · 磨砂蓝调 + 悬浮卡片 + 建筑透视背景',
    source: '#uploaded-image-9',
    tokens: {
        pageBg: '#E8F4FF', // 浅天蓝背景
        fontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        cardBg: 'rgba(255, 255, 255, 0.65)', // 半透明白底
        cardBorderColor: 'rgba(255, 255, 255, 0.4)',
        cardBorderWidth: '1px',
        cardRadius: '20px',
        cardShadow: '0 8px 32px rgba(31, 38, 135, 0.1)', // 柔和高斯阴影
        cardBackdropFilter: 'blur(12px) saturate(180%)', // 关键：磨砂玻璃效果
        titleColor: '#1A237E', // 深蓝标题
        descColor: '#5C6BC0', // 中蓝描述
        itemBg: 'rgba(255, 255, 255, 0.4)',
        itemTitleColor: '#1A237E',
        itemDescColor: '#5C6BC0',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0px',
        itemRadius: '16px',
        upColor: '#FF5252', // 绿色收入/正常
        downColor: '#4CAF50', // 红色支出/异常
        btnBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', // 蓝紫渐变按钮
        btnColor: '#FFFFFF',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', sans-serif",
        btnShadow: '0 4px 16px rgba(102, 126, 234, 0.3)',
        tagBg: 'rgba(102, 126, 234, 0.1)',
        tagColor: '#667eea',
        tagFontFamily: "'Inter', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '8px',
        // 特有玻璃拟态 & 数据可视化 Tokens
        glassOverlay: 'linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0))',
        chartLineColor: '#667eea',
        chartGridColor: 'rgba(102, 126, 234, 0.1)',
        statValueColor: '#1A237E',
        statLabelColor: '#5C6BC0',
        navActiveBg: 'rgba(102, 126, 234, 0.15)',
        navActiveColor: '#667eea',
        navInactiveColor: '#9FA8DA',
        floatingCardZIndex: '100',
        backgroundBlurIntensity: '8px',
        accentGradientStart: '#667eea',
        accentGradientEnd: '#764ba2',
        iconActiveColor: '#667eea',
        iconInactiveColor: '#9FA8DA',
        tooltipBg: 'rgba(255, 255, 255, 0.9)',
        tooltipColor: '#1A237E',
        tooltipBorder: '1px solid rgba(102, 126, 234, 0.2)',
    },
},
{
    id: 'warm-learning-dashboard',
    name: '暖橙学术仪表盘',
    desc: 'Warm Learning Dashboard · 暖橙柔调 + 多彩卡片 + 3D悬浮插图',
    source: '#uploaded-image-1',
    tokens: {
        pageBg: '#FFC8A2', // 暖橙色背景
        fontFamily: "'Plus Jakarta Sans', 'Inter', -apple-system, sans-serif",
        numberFontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
        cardBg: '#F8F6F4', // 米白色主主板背景
        cardBorderColor: 'transparent',
        cardBorderWidth: '0px',
        cardRadius: '24px',
        cardShadow: '0 20px 40px rgba(220, 120, 70, 0.15)',
        cardBackdropFilter: 'none',
        titleColor: '#1E1E24', // 深灰/近黑主标题
        descColor: '#7A7A85', // 中灰次要描述
        itemBg: '#FFFFFF', // 纯白子卡片背景
        itemTitleColor: '#1E1E24',
        itemDescColor: '#7A7A85',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0px',
        itemRadius: '16px',
        upColor: '#FF6B50', // 品牌主橙色（高亮/警示/按钮）
        downColor: '#4ECDC4', // 薄荷绿/辅助色
        btnBg: '#FF6B50', // 亮橙色主按钮
        btnColor: '#FFFFFF',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Plus Jakarta Sans', sans-serif",
        btnShadow: '0 8px 16px rgba(255, 107, 80, 0.25)',
        tagBg: '#F5F5F7',
        tagColor: '#7A7A85',
        tagFontFamily: "'Plus Jakarta Sans', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '8px',
        // 特有色彩卡片与仪表盘 Tokens
        primaryAccent: '#FF6B50', // 主色调：珊瑚橙
        cardPinkBg: '#F9D8D6', // 粉红卡片背景 (Assignments due)
        cardPinkColor: '#D9534F',
        cardGreenBg: '#D2F3E0', // 浅绿卡片背景 (Assignments to check)
        cardGreenColor: '#2E7D32',
        cardPurpleBg: '#E0DBFF', // 浅紫卡片背景 (Free time slots)
        cardPurpleColor: '#5C46E5',
        cardOrangeBg: '#FFE6D2', // 浅橙卡片背景 (Classes this week)
        cardOrangeColor: '#E66A2C',
        navActiveBg: '#FF6B50',
        navActiveColor: '#FFFFFF',
        navInactiveBg: '#FFFFFF',
        navInactiveColor: '#9E9EA7',
        calendarHighlightBg: '#FF8A65',
        calendarHighlightColor: '#FFFFFF',
        schedulePurpleBg: '#E8E5FF',
        scheduleOrangeBg: '#FFF0E5',
        scheduleGreenBg: '#E1F8ED',
        iconActiveColor: '#FFFFFF',
        iconInactiveColor: '#9E9EA7',
        sidebarBg: '#FFFFFF',
        sidebarRadius: '20px'
    },
},
{
    id: 'apeluid-electric-purple',
    name: 'Apeluid 电光紫风格',
    desc: 'Apeluid Electric Purple · 暗黑高饱和紫 + 极简大圆角卡片 + 多色交互胶囊标签',
    source: '#uploaded-image',
    tokens: {
        pageBg: '#0A0A12', // 极深黑紫背景
        fontFamily: "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        cardBg: '#3B38EE', // 高饱和宝蓝/亮紫主卡片底色
        cardBorderColor: 'transparent',
        cardBorderWidth: '0px',
        cardRadius: '24px', // 大圆角卡片
        cardShadow: '0 12px 40px rgba(0, 0, 0, 0.35)', // 深邃阴影
        cardBackdropFilter: 'none',
        titleColor: '#FFFFFF', // 纯白标题
        descColor: 'rgba(255, 255, 255, 0.7)', // 半透明白描述文字
        itemBg: '#12102B', // 卡片内部深色子项/胶囊底色
        itemTitleColor: '#FFFFFF',
        itemDescColor: 'rgba(255, 255, 255, 0.6)',
        itemBorderColor: 'rgba(255, 255, 255, 0.15)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '999px',
        upColor: '#A855F7', // 亮紫色（上升/强调）
        downColor: '#38BDF8', // 青蓝色（下降/辅助）
        btnBg: '#0D0B18', // 黑色纯色胶囊按钮
        btnColor: '#FFFFFF',
        btnRadius: '999px', // 纯圆角胶囊
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', sans-serif",
        btnShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
        tagBg: '#D8B4FE', // 淡紫粉胶囊标签背景
        tagColor: '#3B38EE', // 主色文字
        tagFontFamily: "'Inter', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '999px',
        // 特有视觉 & 渐变 Tokens
        glassOverlay: 'linear-gradient(135deg, rgba(255,255,255,0.15), rgba(255,255,255,0))',
        chartLineColor: '#A855F7',
        chartGridColor: 'rgba(255, 255, 255, 0.1)',
        statValueColor: '#FFFFFF',
        statLabelColor: 'rgba(255, 255, 255, 0.7)',
        navActiveBg: '#3B38EE',
        navActiveColor: '#FFFFFF',
        navInactiveColor: 'rgba(255, 255, 255, 0.4)',
        floatingCardZIndex: '100',
        backgroundBlurIntensity: '0px',
        accentGradientStart: '#3B38EE',
        accentGradientEnd: '#C084FC', // 蓝紫到粉紫渐变
        iconActiveColor: '#FFFFFF',
        iconInactiveColor: 'rgba(255, 255, 255, 0.5)',
        tooltipBg: '#0D0B18',
        tooltipColor: '#FFFFFF',
        tooltipBorder: '1px solid rgba(255, 255, 255, 0.1)',
    },
},
{
    id: 'kiddora-playful-kids-learning',
    name: 'Kiddora 欢快儿童教育风格',
    desc: 'Kiddora Playful Kids Learning · 暖调奶油渐变底色 + 缤纷彩色高饱和元素 + 柔和通透悬浮卡片',
    source: '#uploaded-image-6',
    tokens: {
        pageBg: 'linear-gradient(180deg, #FFF5EE 0%, #FAF0E6 50%, #F5E6FF 100%)', // 暖粉杏色到柔紫渐变背景[cite: 6]
        fontFamily: "'Fredoka', 'Quicksand', -apple-system, sans-serif", // 圆润亲和的儿童字体风格[cite: 6]
        numberFontFamily: "'Fredoka', 'Quicksand', monospace",
        cardBg: 'rgba(255, 255, 255, 0.85)', // 柔和半透明纯白悬浮卡片[cite: 6]
        cardBorderColor: 'rgba(255, 255, 255, 0.9)',
        cardBorderWidth: '1.5px',
        cardRadius: '32px', // 特大超圆润卡片圆角[cite: 6]
        cardShadow: '0 16px 40px rgba(108, 92, 231, 0.08)', // 柔和紫调散发阴影
        cardBackdropFilter: 'blur(10px)',
        titleColor: '#3A2898', // 浓郁深紫标题[cite: 6]
        descColor: '#5D6B98', // 柔和蓝灰描述文字[cite: 6]
        itemBg: '#FFF9E6', // 暖黄子项背景
        itemTitleColor: '#3A2898',
        itemDescColor: '#5D6B98',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0px',
        itemRadius: '20px',
        upColor: '#FF3D00', // 活力绿
        downColor: '#00C853', // 活力橙红
        btnBg: '#6C5CE7', // 鲜亮紫色圆形/胶囊按钮[cite: 6]
        btnColor: '#FFFFFF', // 纯白按钮文本/图标[cite: 6]
        btnRadius: '999px', // 纯圆按钮[cite: 6]
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Fredoka', sans-serif",
        btnShadow: '0 8px 20px rgba(108, 92, 231, 0.35)', // 亮紫色柔和阴影
        tagBg: '#FFEAA7', // 明黄标签/装饰色[cite: 6]
        tagColor: '#D63031',
        tagFontFamily: "'Fredoka', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '999px',
        // 儿童教育与多色主题 Tokens
        glassOverlay: 'none',
        chartLineColor: '#6C5CE7',
        chartGridColor: 'rgba(108, 92, 231, 0.05)',
        statValueColor: '#3A2898',
        statLabelColor: '#5D6B98',
        navActiveBg: '#6C5CE7', // 活跃指示点紫色[cite: 6]
        navActiveColor: '#FFFFFF',
        navInactiveColor: '#D6D1F8', // 未选中指示点浅灰紫[cite: 6]
        floatingCardZIndex: '100',
        backgroundBlurIntensity: '8px',
        accentGradientStart: '#6C5CE7', // 活力紫[cite: 6]
        accentGradientEnd: '#FF7675', // 珊瑚粉[cite: 6]
        iconActiveColor: '#FFFFFF',
        iconInactiveColor: '#A29BFE',
        tooltipBg: '#FFFFFF',
        tooltipColor: '#3A2898',
        tooltipBorder: '1px solid rgba(108, 92, 231, 0.15)',
        // Kiddora 缤纷儿童特有色盘 Tokens
        brandBlue: '#2D52E5', // Logo 蓝[cite: 6]
        brandOrange: '#FF9F1C', // Logo 橙[cite: 6]
        brandCyan: '#00CECB', // Logo 青蓝[cite: 6]
        brandYellow: '#FFD166', // 3D星星暖黄[cite: 6]
        paginationDotActive: '#6C5CE7', // 分页指示器激活点[cite: 6]
        paginationDotInactive: '#E0D8F9', // 分页指示器未激活点[cite: 6]
    },
},
{
    id: 'kiddora-discover-3d-clay',
    name: 'Kiddora 3D立体探究教育风格',
    desc: 'Kiddora Discover 3D Clay · 梦幻淡紫柔粉底色 + 3D粘土软萌图标 + 高饱和圆角悬浮面板',
    source: '#uploaded-image-7',
    tokens: {
        pageBg: 'linear-gradient(180deg, #F8F3FF 0%, #FAF0F8 50%, #F5ECFF 100%)', // 梦幻极浅紫到粉紫渐变背景[cite: 7]
        fontFamily: "'Fredoka', 'Quicksand', -apple-system, sans-serif", // 圆润亲和儿童字体[cite: 7]
        numberFontFamily: "'Fredoka', 'Quicksand', monospace",
        cardBg: 'rgba(255, 255, 255, 0.9)', // 半透明高亮纯白悬浮面板[cite: 7]
        cardBorderColor: 'rgba(255, 255, 255, 0.95)',
        cardBorderWidth: '1.5px',
        cardRadius: '32px', // 大圆角悬浮卡片[cite: 7]
        cardShadow: '0 16px 36px rgba(138, 92, 246, 0.08)', // 浅紫弥散柔阴影
        cardBackdropFilter: 'blur(12px)',
        titleColor: '#1E1B4B', // 深蓝紫标题[cite: 7]
        descColor: '#52525B', // 柔和灰紫描述文字[cite: 7]
        itemBg: '#F5F3FF', // 功能图标浅紫子项底色[cite: 7]
        itemTitleColor: '#1E1B4B',
        itemDescColor: '#52525B',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0px',
        itemRadius: '20px',
        upColor: '#F43F5E', // 活力绿[cite: 7]
        downColor: '#10B981', // 活力粉红[cite: 7]
        btnBg: '#7C3AED', // 鲜亮紫罗兰渐变/纯色按钮[cite: 7]
        btnColor: '#FFFFFF', // 纯白箭头图标/文本[cite: 7]
        btnRadius: '999px', // 圆形前进按钮[cite: 7]
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Fredoka', sans-serif",
        btnShadow: '0 8px 20px rgba(124, 58, 237, 0.35)', // 紫罗兰发光阴影
        tagBg: '#EDE9FE', // 浅紫胶囊标签背景[cite: 7]
        tagColor: '#6D28D9',
        tagFontFamily: "'Fredoka', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '999px',
        // 3D粘土 & 多色儿童功能分类 Tokens
        glassOverlay: 'none',
        chartLineColor: '#7C3AED',
        chartGridColor: 'rgba(124, 58, 237, 0.05)',
        statValueColor: '#1E1B4B',
        statLabelColor: '#52525B',
        navActiveBg: '#7C3AED', // 分页激活指示点[cite: 7]
        navActiveColor: '#FFFFFF',
        navInactiveColor: '#DDD6FE', // 未激活指示点[cite: 7]
        floatingCardZIndex: '100',
        backgroundBlurIntensity: '8px',
        accentGradientStart: '#7C3AED', // 主紫罗兰色[cite: 7]
        accentGradientEnd: '#EC4899', // 亮粉红[cite: 7]
        iconActiveColor: '#FFFFFF',
        iconInactiveColor: '#A78BFA',
        tooltipBg: '#FFFFFF',
        tooltipColor: '#1E1B4B',
        tooltipBorder: '1px solid rgba(124, 58, 237, 0.15)',
        // 3D 粘土图标与多元分类特色 Tokens
        clayPurpleBg: '#C084FC', // 3D书本图标紫底[cite: 7]
        clayPinkBg: '#FB7185', // 3D画板图标粉红底[cite: 7]
        clayGreenBg: '#34D399', // 3D烧杯图标薄荷绿底[cite: 7]
        clayBlueLaptop: '#A5B4FC', // 3D笔记本电脑柔紫蓝[cite: 7]
        clayYellowAccent: '#FBBF24', // 装饰小线条与星号暖黄[cite: 7]
    },
},
{
    id: 'upfound-emerald-dark-gradient',
    name: 'UpFound 极光翡翠暗黑渐变',
    desc: 'UpFound Emerald Dark · 深邃黑绿径向渐变背景 + 宝石绿亮色高光 + 极简现代化文字与胶囊按钮',
    source: '#uploaded-image-10',
    tokens: {
        pageBg: 'radial-gradient(circle at 50% 50%, #0D2D2A 0%, #040A0A 80%)', // 深绿到暗黑渐变背景[cite: 10, 11]
        fontFamily: "'PP Neue Montreal', 'Inter', -apple-system, sans-serif", // 第二图指定的字体[cite: 11]
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        cardBg: 'rgba(255, 255, 255, 0.05)', // 微透暗色玻璃卡片[cite: 10]
        cardBorderColor: 'rgba(255, 255, 255, 0.1)',
        cardBorderWidth: '1px',
        cardRadius: '24px', // 圆润大卡片[cite: 10]
        cardShadow: '0 20px 50px rgba(4, 10, 10, 0.8)', // 极深沉浸式阴影[cite: 11]
        cardBackdropFilter: 'blur(16px)',
        titleColor: '#FFFFFF', // 纯白高亮标题[cite: 10, 11]
        descColor: 'rgba(255, 255, 255, 0.7)', // 半透明白次要文字[cite: 10]
        itemBg: 'rgba(255, 255, 255, 0.08)', // 胶囊导航/次级按钮微透背景[cite: 10]
        itemTitleColor: '#FFFFFF',
        itemDescColor: 'rgba(255, 255, 255, 0.6)',
        itemBorderColor: 'rgba(255, 255, 255, 0.12)',
        itemBorderStyle: 'solid',
        itemBorderWidth: '1px',
        itemRadius: '999px',
        upColor: '#22F2EF', // 第二图色板：荧光绿（涨/成功率）[cite: 10, 11]
        downColor: '#3EE97D', // 第二图色板：青蓝[cite: 11]
        btnBg: 'linear-gradient(135deg, #49DC7A 0%, #3EE97D 100%)', // 第二图色板渐变绿行动按钮[cite: 10, 11]
        btnColor: '#040A0A', // 黑色高对比度按钮文字[cite: 10, 11]
        btnRadius: '999px', // 纯圆胶囊按钮[cite: 10]
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'PP Neue Montreal', sans-serif", // 指定字体[cite: 11]
        btnShadow: '0 8px 24px rgba(62, 233, 125, 0.3)', // 荧光绿发光散影[cite: 11]
        tagBg: 'rgba(73, 220, 122, 0.15)',
        tagColor: '#49DC7A', // 第二图色板：薄荷绿[cite: 11]
        tagFontFamily: "'PP Neue Montreal', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '999px',
        // 图纸特定 & 第二图 Palette 指定 Token
        glassOverlay: 'linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0))',
        chartLineColor: '#3EE97D',
        chartGridColor: 'rgba(255, 255, 255, 0.05)',
        statValueColor: '#FFFFFF',
        statLabelColor: 'rgba(255, 255, 255, 0.6)',
        navActiveBg: 'rgba(255, 255, 255, 0.15)',
        navActiveColor: '#FFFFFF',
        navInactiveColor: 'rgba(255, 255, 255, 0.6)',
        floatingCardZIndex: '100',
        backgroundBlurIntensity: '16px',
        accentGradientStart: '#49DC7A', // 色板 1：#49DC7A[cite: 11]
        accentGradientEnd: '#22F2EF', // 色板 3：#22F2EF[cite: 11]
        iconActiveColor: '#3EE97D',
        iconInactiveColor: 'rgba(255, 255, 255, 0.4)',
        tooltipBg: '#040A0A', // 色板 4：#040A0A[cite: 11]
        tooltipColor: '#FFFFFF', // 色板 5：#FFFFFF[cite: 11]
        tooltipBorder: '1px solid rgba(73, 220, 122, 0.2)',
        // Palette 精确对应色值列表（来自图二）
        paletteDarkBg: '#040A0A', // 深纯黑背景底色[cite: 11]
        palettePureWhite: '#FFFFFF', // 纯白文字/元素[cite: 11]
        paletteMintGreen: '#49DC7A', // 薄荷绿[cite: 11]
        paletteNeonGreen: '#3EE97D', // 鲜亮荧光绿[cite: 11]
        paletteElectricCyan: '#22F2EF', // 电光青蓝[cite: 11]
        typographyFont: 'PP Neue Montreal', // 指定排版字体[cite: 11]
    },
},
{
    id: 'strava-yearly-sport',
    name: 'Strava年度燃动',
    desc: 'Strava Yearly Sport · 紫橙流体渐变 + 粗体数据叙事 + 胶囊标签',
    source: '#uploaded-image-12',
    tokens: {
        pageBg: 'linear-gradient(160deg, #4C1D95 0%, #7C3AED 25%, #EC4899 55%, #F97316 85%, #FBBF24 100%)',
        fontFamily: "'Helvetica Now Display', 'Inter', -apple-system, sans-serif",
        numberFontFamily: "'DIN Alternate', 'Barlow Condensed', sans-serif",
        cardBg: 'rgba(255, 255, 255, 0.12)',
        cardBorderColor: 'rgba(255, 255, 255, 0.2)',
        cardBorderWidth: '1px',
        cardRadius: '24px',
        cardShadow: '0 12px 40px rgba(76, 29, 149, 0.3)',
        cardBackdropFilter: 'blur(16px) saturate(180%)',
        titleColor: '#FFFFFF',
        descColor: 'rgba(255, 255, 255, 0.85)',
        itemBg: 'rgba(255, 255, 255, 0.08)',
        itemTitleColor: '#FFFFFF',
        itemDescColor: 'rgba(255, 255, 255, 0.75)',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0px',
        itemRadius: '16px',
        upColor: '#00D4FF',
        downColor: '#00FFC2', // 冰蓝：在橙黄区靠冷色相+高明度双重跳出，深紫区同样清晰
        btnBg: '#FFFFFF',
        btnColor: '#7C3AED',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Helvetica Now Display', sans-serif",
        btnShadow: '0 4px 16px rgba(255, 255, 255, 0.25)',
        tagBg: 'rgba(255, 255, 255, 0.2)',
        tagColor: '#FFFFFF',
        tagFontFamily: "'Helvetica Now Display', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '999px',
        activityIconColor: '#FFFFFF',
        distanceHighlight: '#FBBF24',
        elevationGradient: 'linear-gradient(to top, rgba(255,255,255,0.1), rgba(255,255,255,0.3))',
        weeklyChartBar: 'rgba(255, 255, 255, 0.6)',
        weeklyChartActiveBar: '#FFFFFF',
        achievementBadgeBg: 'rgba(251, 191, 36, 0.2)',
        achievementBadgeColor: '#FBBF24',
        mapOverlay: 'rgba(76, 29, 149, 0.4)',
        mapRouteLine: '#FFFFFF',
        statDivider: 'rgba(255, 255, 255, 0.15)',
        sectionTitleWeight: '800',
        dataValueWeight: '700',
        navActiveBg: 'rgba(255, 255, 255, 0.25)',
        navActiveColor: '#FFFFFF',
        navInactiveColor: 'rgba(255, 255, 255, 0.6)',
        tooltipBg: 'rgba(0, 0, 0, 0.7)',
        tooltipColor: '#FFFFFF',
        tooltipBorder: 'none',
        pulseAnimation: 'animation: glow-white 2.5s ease-in-out infinite',
        gradientText: 'background: linear-gradient(90deg, #FBBF24, #FFFFFF); -webkit-background-clip: text; color: transparent;',
    },
},
{
    id: 'focus-workflow-dashboard',
    name: 'Focus 工作流',
    desc: 'Focus Workflow · 深空灰玻璃拟态 + 霓虹数据流 + 圆角任务系统',
    source: '#uploaded-image-13',
    tokens: {
        // ✨ 核心背景：深邃蓝灰渐变，模拟夜空或深海，为霓虹色提供最佳画布
        pageBg: 'linear-gradient(180deg, #0F172A 0%, #1E293B 100%)',
        fontFamily: "'Inter', 'SF Pro Text', -apple-system, sans-serif",
        numberFontFamily: "'JetBrains Mono', 'Fira Code', monospace",
        // 卡片采用高透+强模糊，边框极细，营造悬浮感
        cardBg: 'rgba(30, 41, 51, 0.65)',
        cardBorderColor: 'rgba(255, 255, 255, 0.08)',
        cardBorderWidth: '1px',
        cardRadius: '20px',
        cardShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
        cardBackdropFilter: 'blur(24px) saturate(180%)',
        titleColor: '#FFFFFF',
        descColor: '#CBD5E1',
        itemBg: 'rgba(51, 65, 85, 0.4)',
        itemTitleColor: '#FFFFFF',
        itemDescColor: '#94A3B8',
        itemBorderColor: 'transparent',
        itemBorderStyle: 'solid',
        itemBorderWidth: '0px',
        itemRadius: '16px',
        // ✨ 霓虹三色系统：紫（主任务）、粉（紧急/创意）、黄（时间轴/高亮）
        upColor: '#EC4899',   // 荧光紫：用于进度增长、完成度
        downColor: '#A855F7', // 荧光粉：用于警告、未完成、创意爆发
        btnBg: 'linear-gradient(135deg, #EC4899 0%, #A855F7 100%)',
        btnColor: '#FFFFFF',
        btnRadius: '999px',
        btnBorderColor: 'transparent',
        btnBorderStyle: 'solid',
        btnBorderWidth: '0px',
        btnFontFamily: "'Inter', sans-serif",
        btnShadow: '0 4px 16px rgba(236, 72, 153, 0.3)',
        tagBg: 'rgba(168, 85, 247, 0.15)',
        tagColor: '#C084FC',
        tagFontFamily: "'Inter', sans-serif",
        tagBorderColor: 'transparent',
        tagBorderStyle: 'solid',
        tagBorderWidth: '0px',
        tagRadius: '8px',
        // 特有工作流 Tokens
        progressBarBg: 'rgba(51, 65, 85, 0.6)',
        progressBarFill: '#A855F7',
        calendarTodayBg: 'rgba(168, 85, 247, 0.2)',
        calendarTodayColor: '#FFFFFF',
        calendarWeekendColor: '#64748B',
        timelineCurrentLine: '#FBBF24', // 黄色垂直线
        timelineBarBg: 'rgba(51, 65, 85, 0.6)',
        timelineBarActive: '#A855F7',
        timelineBarPending: 'rgba(255, 255, 255, 0.1)',
        chatBubbleUser: 'rgba(168, 85, 247, 0.2)',
        chatBubbleOther: 'rgba(51, 65, 85, 0.6)',
        chatTextColor: '#FFFFFF',
        avatarRingColor: 'rgba(255, 255, 255, 0.2)',
        notificationBadgeBg: '#A855F7',
        notificationBadgeColor: '#FFFFFF',
        searchInputBg: 'rgba(30, 41, 51, 0.4)',
        searchInputColor: '#FFFFFF',
        searchInputPlaceholder: '#64748B',
        navActiveBg: 'rgba(168, 85, 247, 0.15)',
        navActiveColor: '#C084FC',
        navInactiveColor: '#64748B',
        tooltipBg: 'rgba(15, 23, 42, 0.95)',
        tooltipColor: '#FFFFFF',
        tooltipBorder: '1px solid rgba(168, 85, 247, 0.3)',
        pulseAnimation: 'animation: pulse-purple 2s infinite',
        glowEffect: 'box-shadow: 0 0 20px rgba(168, 85, 247, 0.4)',
    },
}

];

// 根据 id 获取主题包；'' / undefined / 'default' 返回 null（默认样式）
export const getThemePack = (id) => {
    if (!id || id === 'default') return null;
    return THEME_PACKS.find(p => p.id === id) || null;
};

// 将主题包 token 转为 CSS 变量 style 对象（用于 React style / 挂到容器上）
export const buildPackVars = (pack) => {
    if (!pack?.tokens) return undefined;
    const t = pack.tokens;
    const vars = {};
    Object.entries(TOKEN_TO_VAR).forEach(([key, varName]) => {
        const val = t[key];
        if (val !== undefined && val !== null && val !== '') {
            vars[varName] = val;
        }
    });
    // 派生涨跌标签底色（半透明）
    if (!vars['--dp-up-bg'] && t.upColor) vars['--dp-up-bg'] = hexToRgba(t.upColor, 0.14);
    if (!vars['--dp-down-bg'] && t.downColor) vars['--dp-down-bg'] = hexToRgba(t.downColor, 0.14);
    return vars;
};
